force-app/main/default/objects/AccountDepositor__c/AccountDepositor__c.object-meta.xml
<CustomObject>
    <label>Account Depositor</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Depositors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountDepositor__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Depositors</relationshipLabel>
    <relationshipName>AccountDepositor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountDepositor__c/fields/Depositor__c.field-meta.xml
<CustomField>
    <fullName>Depositor__c</fullName>
    <label>Depositor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/BankTransaction__c.object-meta.xml
<CustomObject>
    <label>Bank Transaction</label>
    <nameField>
        <displayFormat>BT-{YYMMDD}-{00000}</displayFormat>
        <label>Bank Transaction No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BankTransaction__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Transactions</relationshipLabel>
    <relationshipName>BankTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/Depositor__c.field-meta.xml
<CustomField>
    <fullName>Depositor__c</fullName>
    <label>Depositor</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/NetBalanceAftCleared__c.field-meta.xml
<CustomField>
    <fullName>NetBalanceAftCleared__c</fullName>
    <label>Not-Reconciled AMT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/OriginAmount__c.field-meta.xml
<CustomField>
    <fullName>OriginAmount__c</fullName>
    <label>Origin Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/TotalClearedAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalClearedAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Reconciled AMT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <label>TransactionType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BankTransaction_tr.cls
/**
 * @description       :
 * @author            : Yugon Hwang
 * @last modified on  : 2026-04-24
 * @last modified by  : Akrom Saidkamolov
 **/
public without sharing class BankTransaction_tr extends TriggerHandler {
    private Map<Id, BankTransaction__c> mapNew;
    private Map<Id, BankTransaction__c> mapOld;
    private List<BankTransaction__c> listNew;
    private List<BankTransaction__c> listOld;

    public BankTransaction_tr() {
        this.mapNew = (Map<Id, BankTransaction__c>) Trigger.newMap;
        this.mapOld = (Map<Id, BankTransaction__c>) Trigger.oldMap;
        this.listNew = (List<BankTransaction__c>) Trigger.new;
        this.listOld = (List<BankTransaction__c>) Trigger.old;
    }

    public override void beforeInsert() {
        assignBizRegion();
        assignMatchAccount();
        setInitialValues();
    }

    public override void beforeUpdate() {
        calculateNotReconciledAmount();
    }

    public override void beforeDelete() {
        //- BT 삭제 시 Status 확인
        for (BankTransaction__c bt : listOld) {
            if (bt.Status__c != REC_Consts.BankTransactionStatus.NONE) {
                bt.addError('Cannot delete Bank Transaction with Status other than None');
            }
        }
    }

    private void calculateNotReconciledAmount() {
        for (BankTransaction__c bt : listNew) {
            //- 해당 BT의 Reconciled Amount = 0인 경우 Origin Amount 변경 시 Not-Reconciled AMT 값도 업데이트
            //- 해당 BT의 Reconciled Amount ≠ 0인 경우, 수정 저장 시 오류 표시
            if (mapOld.get(bt.Id).OriginAmount__c != bt.OriginAmount__c) {
                if (bt.TotalClearedAmount__c != null && bt.TotalClearedAmount__c != 0) {
                    bt.addError('Cannot update Origin Amount when Total Cleared Amount is not 0');
                } else {
                    bt.NetBalanceAftCleared__c = bt.OriginAmount__c;
                }
            }
        }
    }

    private void assignBizRegion() {
        for (BankTransaction__c bt : listNew) {
            if (bt.BizRegion__c == null) {
                bt.BizRegion__c = Util.getBizRegion();
            }
        }
    }

    private void assignMatchAccount() {
        Set<String> setBizRegion = new Set<String>();
        Set<String> setDepositor = new Set<String>();

        for (BankTransaction__c bt : listNew) {
            if (String.isNotBlank(bt.Depositor__c) && String.isNotBlank(bt.BizRegion__c) && bt.AccountName__c == null) {
                setDepositor.add(bt.Depositor__c);
                setBizRegion.add(bt.BizRegion__c);
            }
        }

        if (setDepositor.isEmpty()) {
            return;
        }

        Map<String, Id> mapAccountByKey = new Map<String, Id>();
        for (AccountDepositor__c ad : [
            SELECT BizRegion__c, Depositor__c, AccountName__c
            FROM AccountDepositor__c
            WHERE
                Depositor__c IN :setDepositor
                AND AccountName__c != NULL
                AND IsActive__c = TRUE
                AND BizRegion__c IN :setBizRegion
        ]) {
            mapAccountByKey.put(ad.BizRegion__c + '_' + ad.Depositor__c, ad.AccountName__c);
        }

        for (BankTransaction__c bt : listNew) {
            if (String.isNotBlank(bt.Depositor__c) && String.isNotBlank(bt.BizRegion__c) && bt.AccountName__c == null) {
                String key = bt.BizRegion__c + '_' + bt.Depositor__c;
                if (mapAccountByKey.containsKey(key)) {
                    bt.AccountName__c = mapAccountByKey.get(key);
                }
            }
        }
    }

    private void setInitialValues() {
        for (BankTransaction__c bt : listNew) {
            if (bt.TransactionType__c == BankTransactionService.TRANSACTION_TYPE_WITHDRAWAL && bt.OriginAmount__c > 0) {
                bt.OriginAmount__c = bt.OriginAmount__c * -1;
            }
            if (bt.NetBalanceAftCleared__c == null) {
                bt.NetBalanceAftCleared__c = bt.OriginAmount__c;
            }
        }
    }
}