force-app/main/default/objects/ACC_AdditionalInfo__c/ACC_AdditionalInfo__c.object-meta.xml
<CustomObject>
    <label>Additional Account Info</label>
    <nameField>
        <label>Account Additional Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Account Info</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ACC_AdditionalInfo__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ACC_AdditionalInfo__c/fields/Reinsurer_lk__c.field-meta.xml
<CustomField>
    <fullName>Reinsurer_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reinsurer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Additional Account Info (Reinsurer)</relationshipLabel>
    <relationshipName>AdditionalAcctInfosAsReinsurer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/COM_Facility__c/COM_Facility__c.object-meta.xml
<CustomObject>
    <description>Facility Master 정보 관리(기회, 계약 연계)</description>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/COM_Facility__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/OPP_Layer__c.object-meta.xml
<CustomObject>
    <label>Layer</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Layer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Layers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Layer__c/fields/Excess__c.field-meta.xml
<CustomField>
    <fullName>Excess__c</fullName>
    <label>Excess (Deductible)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/fields/Layer_fm__c.field-meta.xml
<CustomField>
    <fullName>Layer_fm__c</fullName>
    <formula>IF( ISPICKVAL(Type__c , &apos;QS&apos;),
			/* Type이 &apos;QS&apos;일 때:QS */
			&apos;QS&apos;,
			IF(
				
				Excess__c = 0,
    /* Excess가 0일 때: LOL xs OPDs */
    IF(ABS(LOL__c) &gt;= 1000000000000, TEXT(LOL__c / 1000000000000) &amp; &quot;tr&quot;,
    IF(ABS(LOL__c) &gt;= 1000000000, TEXT(LOL__c / 1000000000) &amp; &quot;bn&quot;,
    IF(ABS(LOL__c) &gt;= 1000000, TEXT(LOL__c / 1000000) &amp; &quot;M&quot;,
    TEXT(LOL__c)))) &amp; &quot; xs OPDs&quot;,

    /* Excess가 0이 아닐 때: LOL xs Excess xs OPDs */
    IF(ABS(LOL__c) &gt;= 1000000000000, TEXT(LOL__c / 1000000000000) &amp; &quot;tr&quot;,
    IF(ABS(LOL__c) &gt;= 1000000000, TEXT(LOL__c / 1000000000) &amp; &quot;bn&quot;,
    IF(ABS(LOL__c) &gt;= 1000000, TEXT(LOL__c / 1000000) &amp; &quot;M&quot;,
    TEXT(LOL__c)))) 
    &amp; &quot; xs &quot; &amp; 
    IF(ABS(Excess__c) &gt;= 1000000000000, TEXT(Excess__c / 1000000000000) &amp; &quot;tr&quot;,
    IF(ABS(Excess__c) &gt;= 1000000000, TEXT(Excess__c / 1000000000) &amp; &quot;bn&quot;,
    IF(ABS(Excess__c) &gt;= 1000000, TEXT(Excess__c / 1000000) &amp; &quot;M&quot;,
    TEXT(Excess__c)))) 
    &amp; &quot; xs OPDs&quot;
							)
)</formula>
    <label>Layer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/fields/LayerCurrency__c.field-meta.xml
<CustomField>
    <fullName>LayerCurrency__c</fullName>
    <label>Layer Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/fields/LOL__c.field-meta.xml
<CustomField>
    <fullName>LOL__c</fullName>
    <label>LOL (Limit)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QS</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
            <value>
                <fullName>Umbrella</fullName>
            </value>
            <value>
                <fullName>Brkg Adj</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/OPP_Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Panel__c/fields/ActualAdjRatePct__c.field-meta.xml
<CustomField>
    <fullName>ActualAdjRatePct__c</fullName>
    <label>Actual Adj Rate (%)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/BrkgAdj_is__c.field-meta.xml
<CustomField>
    <fullName>BrkgAdj_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brkg Adj (Y/N)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/BrkgBase__c.field-meta.xml
<CustomField>
    <fullName>BrkgBase__c</fullName>
    <label>Brokerage Base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net</fullName>
            </value>
            <value>
                <fullName>Gross</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/CO_is__c.field-meta.xml
<CustomField>
    <fullName>CO_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/CoBroker_lk__c.field-meta.xml
<CustomField>
    <fullName>CoBroker_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Panels (Co-borker Name)</relationshipLabel>
    <relationshipName>PanelsAsCoBroker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/DPPct__c.field-meta.xml
<CustomField>
    <fullName>DPPct__c</fullName>
    <defaultValue>100</defaultValue>
    <label>DP(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Excess__c.field-meta.xml
<CustomField>
    <fullName>Excess__c</fullName>
    <label>Excess</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Facility_lk__c.field-meta.xml
<CustomField>
    <fullName>Facility_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>COM_Facility__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>PanelsAsFacility</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Finalize_is__c.field-meta.xml
<CustomField>
    <fullName>Finalize_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Finalize</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/GrossPrem__c.field-meta.xml
<CustomField>
    <fullName>GrossPrem__c</fullName>
    <label>Gross Prem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/GrossPremDP__c.field-meta.xml
<CustomField>
    <fullName>GrossPremDP__c</fullName>
    <label>Gross Prem(Before DP)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Layer_md__c.field-meta.xml
<CustomField>
    <fullName>Layer_md__c</fullName>
    <label>Layer</label>
    <referenceTo>OPP_Layer__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Leader_is__c.field-meta.xml
<CustomField>
    <fullName>Leader_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leader</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/LKProducingSharingPct__c.field-meta.xml
<CustomField>
    <fullName>LKProducingSharingPct__c</fullName>
    <label>LK Producing Sharing(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/LOL__c.field-meta.xml
<CustomField>
    <fullName>LOL__c</fullName>
    <label>LOL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/MarketType__c.field-meta.xml
<CustomField>
    <fullName>MarketType__c</fullName>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility</fullName>
            </value>
            <value>
                <fullName>MGA</fullName>
            </value>
            <value>
                <fullName>Open Market</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/MGAName_lk__c.field-meta.xml
<CustomField>
    <fullName>MGAName_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MGA Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Panels (MGA Name)</relationshipLabel>
    <relationshipName>PanelsAsMGA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/NetToLKPrem__c.field-meta.xml
<CustomField>
    <fullName>NetToLKPrem__c</fullName>
    <label>Net to LK Prem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/OtherDeductionPct__c.field-meta.xml
<CustomField>
    <fullName>OtherDeductionPct__c</fullName>
    <label>Other Deduction(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/PlacingSettlementType__c.field-meta.xml
<CustomField>
    <fullName>PlacingSettlementType__c</fullName>
    <label>Settlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Separate</fullName>
            </value>
            <value>
                <fullName>Together</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/PlacingSharingPct__c.field-meta.xml
<CustomField>
    <fullName>PlacingSharingPct__c</fullName>
    <label>Sharing(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/PlacingTPPAdminFeePct__c.field-meta.xml
<CustomField>
    <fullName>PlacingTPPAdminFeePct__c</fullName>
    <label>TPP Admin Fee(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/ProducingSharingPct__c.field-meta.xml
<CustomField>
    <fullName>ProducingSharingPct__c</fullName>
    <label>Sharing(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Reinsurer_lk__c.field-meta.xml
<CustomField>
    <fullName>Reinsurer_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reinsurer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MarketLinesAsReinsurer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/RICommPct__c.field-meta.xml
<CustomField>
    <fullName>RICommPct__c</fullName>
    <label>RI Comm(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Security_lk__c.field-meta.xml
<CustomField>
    <fullName>Security_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Security</label>
    <referenceTo>ACC_AdditionalInfo__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>MarketLinesAsSecurity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Signed__c.field-meta.xml
<CustomField>
    <fullName>Signed__c</fullName>
    <label>Signed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/TotalBrkg__c.field-meta.xml
<CustomField>
    <fullName>TotalBrkg__c</fullName>
    <label>Total Brokerage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/TotalBrkgPct__c.field-meta.xml
<CustomField>
    <fullName>TotalBrkgPct__c</fullName>
    <label>Total Brkg(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Written__c.field-meta.xml
<CustomField>
    <fullName>Written__c</fullName>
    <label>Written</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/COM_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>CNY</fullName>
    </customValue>
    <customValue>
        <fullName>RMB</fullName>
    </customValue>
    <customValue>
        <fullName>STG</fullName>
    </customValue>
    <masterLabel>[COM] Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OPP_MarketLineWrapper.cls
/**********************************************************************************
 * @filename      : OPP_MarketLineWrapper.cls
 * @project-name  : LK보험중계 신규계약관리시스템 구축
 * @author        : i2max
 * @date          : 2026-02-07 (토)
 * @group         :
 * @group-content :
 * @description   :
 * @test-class    : OPP_MarketLineWrapper_ts.cls
 * @reference     :
 * @copyright     : LK Insurance Services
 * @modification  Log
 * ===================================================================
 * ver   date            author           description
 * ===================================================================
 * 1.0   2026-02-07      i2max     Create
**********************************************************************************/
public with sharing class OPP_MarketLineWrapper {

    public enum CellType { text, num, picklist, checkbox, multipicklist, lookup, d, dt, button, textarea, richtext, percent }
    public enum CellMode { VIEW, EDIT, HIDDEN }

    public static final Integer WIDTH_DEFAULT = 120;
    public static final Integer WIDTH_LOOKUP = 170;

    // ============================================================================
    // 1. Grid Meta
    // ============================================================================
    public class GridMeta {
        @AuraEnabled public List<ColMeta> columns {get; set;}
        @AuraEnabled public OPP_MarketLineRuleService.RuleSet rules {get; set;}
        @AuraEnabled public Map<String, Object> ctx {get; set;}
        @AuraEnabled public List<LayerItem> rows {get; set;}
        @AuraEnabled public Boolean isOpp {get; set;}
        @AuraEnabled public Boolean isPlacement {get; set;}
        @AuraEnabled public Boolean isClaim {get; set;}
        @AuraEnabled public Boolean isCICase {get; set;}
        @AuraEnabled public Boolean isReadOnly {get; set;}
        @AuraEnabled public Boolean isTreaty {get; set;}
        @AuraEnabled public String claimCurrency {get; set;}
    }

    // ============================================================================
    // 2. Column Meta
    // ============================================================================
    public class ColMeta {
        @AuraEnabled public String key;
        @AuraEnabled public String label;
        @AuraEnabled public String type;
        @AuraEnabled public String mode;
        @AuraEnabled public Integer rowSpan;
        @AuraEnabled public String groupName;
        @AuraEnabled public Integer width;
        @AuraEnabled public Integer scale;
        @AuraEnabled public Integer precision;
        @AuraEnabled public Boolean isMulti;
        @AuraEnabled public String lookupObject;
        @AuraEnabled public String lookupLabelField;
        @AuraEnabled public String parentField;
        @AuraEnabled public String formula;
        @AuraEnabled public Boolean required;
        @AuraEnabled public List<String> depends;
        @AuraEnabled public List<COM_Option> options;
        /** 그룹 접기/펼치기 가능 여부 (false면 항상 펼침), false 일때 토글 버튼 숨김 처리  */
        @AuraEnabled public Boolean groupCollapsible = true; //해당 그룹이 접힘 가능한지 여부. false면 접기/펼치기 자체가 불가 (항상 펼쳐짐)
        /** 초기 접힘 상태 (true면 로드 시 접힘) */
        @AuraEnabled public Boolean collapsed = false; //해당 그룹의 초기 접힘 상태. true면 화면 로드 시 접힌 채로 시작
        @AuraEnabled public Boolean groupPrimary = false;
        @AuraEnabled public String zeroDisplayText;
        @AuraEnabled public String filterField;
        @AuraEnabled public Object filterValue;
        @AuraEnabled public Map<String, Object> filters;

        public ColMeta(SObjectField sObjectField, CellMode mode, String groupName) {
            this(null, sObjectField, mode, groupName);
        }

        public ColMeta(String key, SObjectField sObjectField, CellMode mode, String groupName) {
            
            this.mode = String.valueOf(mode).toLowerCase();
            this.groupName = groupName;
            this.width = WIDTH_DEFAULT;
            this.isMulti = false;
            this.rowSpan = 1;
            this.required = false;

            if (sObjectField != null) {
                DescribeFieldResult describeFieldResult = sObjectField.getDescribe();
                this.key = describeFieldResult.getName();
                this.label = describeFieldResult.getLabel();
                this.type = mapSfTypeToCellType(describeFieldResult);
                if (this.type == 'num') {
                    this.scale = describeFieldResult.getScale();
                    this.precision = describeFieldResult.getPrecision();
                }
                if (this.type == 'picklist' || this.type == 'multipicklist') {
                    this.options = COM_Util.makePickListOptions(
                            describeFieldResult.SObjectType.getDescribe().getName(),
                            describeFieldResult.getName(),
                            true
                    );
                }
                if (this.type == 'lookup') {
                    if (!describeFieldResult.getReferenceTo().isEmpty()) {
                        this.lookupObject = describeFieldResult.getReferenceTo()[0].getDescribe().getName();
                        this.lookupLabelField = 'Name';
                    }
                    this.width = WIDTH_LOOKUP;
                }
                return;
            }

            this.key   = key;
            this.type  = CellType.text.toString();
            this.label = key;

            if (String.isBlank(key)) {
                throw new AuraHandledException('ColMeta: key is required for virtual columns. key=['+ key +']');
            }
            if (!Pattern.compile('^[A-Za-z_][A-Za-z0-9_]*$').matcher(key).matches()) {
                throw new AuraHandledException('ColMeta: invalid key "' + key + '". Use [A-Za-z_][A-Za-z0-9_]*.');
            }
        }

        public ColMeta label(String v) { this.label = v; return this; }
        public ColMeta scale(Integer v) { this.scale = v; return this; }
        public ColMeta multi(Boolean v) { this.isMulti = v; return this; }
        public ColMeta parentField(String val) { this.parentField = val; return this; }
        public ColMeta lookup(String obj, String labelField) {
            this.type = String.valueOf(CellType.lookup).toLowerCase();
            this.lookupObject = obj;
            this.lookupLabelField = String.isBlank(labelField) ? 'Name' : labelField;
            this.width = WIDTH_LOOKUP;
            return this;
        }
        public ColMeta lookupLabelField(String v) { this.lookupLabelField = v; return this; }
        public ColMeta formula(String val) { this.type = String.valueOf(CellType.text).toLowerCase(); this.formula = val; return this; }
        public ColMeta dependsOn(List<String> d) { this.depends = d; return this; }
        public ColMeta type(CellType type) { this.type = String.valueOf(type).toLowerCase(); return this; }
        public ColMeta options(List<COM_Option> o) { this.type = String.valueOf(CellType.picklist).toLowerCase(); this.options = (o == null) ? new List<COM_Option>() : o; return this; }
        public ColMeta rowSpan(Integer v) { this.rowSpan = v; return this; }
        public ColMeta width(Integer v) { this.width = v; return this; }
        public ColMeta groupName(String v) { this.groupName = v; return this; }
        public ColMeta groupCollapsible(Boolean v) { this.groupCollapsible = v; return this; }
        public ColMeta collapsed(Boolean v) { this.collapsed = v; return this; }
        public ColMeta groupPrimary() { this.groupPrimary = true; return this; }
        public ColMeta required() { this.required = true; return this; }
        public ColMeta viewMode() { this.mode = String.valueOf(CellMode.VIEW).toLowerCase(); return this; }
        public ColMeta editMode() { this.mode = String.valueOf(CellMode.EDIT).toLowerCase(); return this; }
        public ColMeta hiddenMode() { this.mode = String.valueOf(CellMode.HIDDEN).toLowerCase(); return this; }
        public ColMeta zeroDisplayText(String v) { this.zeroDisplayText = v; return this; }
//        public ColMeta filter(String field, Object value) {
//            this.filterField = field;
//            this.filterValue = value;
//            return this;
//        }
        public ColMeta filter(String field, Object value) {
            if (this.filters == null) {
                this.filters = new Map<String, Object>();
            }
            this.filters.put(field, value);

            // 기존 단일 필터 변수도 업데이트 (마지막 설정값 기준 유지)
            this.filterField = field;
            this.filterValue = value;
            return this;
        }

        public ColMeta filters(Map<String, Object> filterMap) {
            if (this.filters == null) this.filters = new Map<String, Object>();
            if (filterMap != null) this.filters.putAll(filterMap);
            return this;
        }

    }

    // ============================================================================
    // 3. Layer Item
    // ============================================================================
    public class LayerItem {
        @AuraEnabled public String Id { get; set; }
        @AuraEnabled public Boolean isDeleted { get; set; }
        @AuraEnabled public Integer layerRowSpan {
            get {
                Integer rowCnt = 1;
                for (MarketLineItem item : marketLineItems) {
                    if (item.isDeleted == false) rowCnt++;
                }
                return rowCnt;
            }
            set;
        }
        @AuraEnabled public Map<String, Object> layerValues;
        @AuraEnabled public List<MarketLineItem> marketLineItems { get; set; }

        public LayerItem(OPP_Layer__c layer) {
            this.Id = layer.Id;
            this.isDeleted = false;
            this.layerValues = new Map<String, Object>{
                    'Type__c'          => layer.Type__c,
                    'LayerCurrency__c' => layer.LayerCurrency__c,
                    'LOL__c'           => layer.LOL__c,
                    'Excess__c'        => layer.Excess__c,
                    'Layer_fm__c'      => layer.Layer_fm__c,
                    'Remarks__c'       => layer.Remarks__c
            };
            this.marketLineItems = new List<MarketLineItem>();
        }
    }

    // ============================================================================
    // 4. Market Line Item
    // ============================================================================
    public class MarketLineItem {
        @AuraEnabled public String Id { get; set; }
        @AuraEnabled public String layerId { get; set; }
        @AuraEnabled public Boolean isDeleted { get; set; }
        @AuraEnabled public Map<String, Object> values;

        public MarketLineItem(OPP_Panel__c panel) {
            this.Id = panel.Id;
            this.layerId = panel.Layer_md__c;
            this.isDeleted = false;

            Map<String, Object> items = new Map<String, Object>();

            items.put('CO_is__c', panel.CO_is__c);//Hidden Field
            items.put('BrkgAdj_is__c', panel.BrkgAdj_is__c);//Hidden Field
            items.put('Finalize_is__c', panel.Finalize_is__c);

            items.put('MarketType__c',        panel.MarketType__c);
            items.put('Currency__c',          panel.Currency__c);
            items.put('Facility_lk__c',       panel.Facility_lk__c);
            if (panel.Facility_lk__r != null) {
                items.put('Facility_lk__r', new Map<String, Object>{ 'Name' => panel.Facility_lk__r.Name });
            }
            items.put('MGAName_lk__c',        panel.MGAName_lk__c);
            if (panel.MGAName_lk__r != null) {
                items.put('MGAName_lk__r', new Map<String, Object>{ 'Name' => panel.MGAName_lk__r.Name });
            }
            items.put('LKProducingSharingPct__c', panel.LKProducingSharingPct__c);
            items.put('Leader_is__c',         panel.Leader_is__c);
            items.put('Reinsurer_lk__c',      panel.Reinsurer_lk__c);
            if (panel.Reinsurer_lk__r != null) {
                items.put('Reinsurer_lk__r', new Map<String, Object>{ 'Name' => panel.Reinsurer_lk__r.Name });
            }
            items.put('Security_lk__c',       panel.Security_lk__c);
            if (panel.Security_lk__r != null) {
                items.put('Security_lk__r', new Map<String, Object>{ 'Name' => panel.Security_lk__r.Name });
            }

            items.put('Written__c',           panel.Written__c);
            items.put('Signed__c',            panel.Signed__c);

            items.put('GrossPremDP__c',       panel.GrossPremDP__c);
            items.put('DPPct__c',             panel.DPPct__c);
            items.put('GrossPrem__c',         panel.GrossPrem__c);
            items.put('ActualAdjRatePct__c',     panel.ActualAdjRatePct__c);
            items.put('RICommPct__c',         panel.RICommPct__c);
            items.put('OtherDeductionPct__c', panel.OtherDeductionPct__c);
            items.put('NetToLKPrem__c',       panel.NetToLKPrem__c);

            items.put('BrkgBase__c',          panel.BrkgBase__c);
            items.put('TotalBrkgPct__c',      panel.TotalBrkgPct__c);
            items.put('TotalBrkg__c',         panel.TotalBrkg__c);

            items.put('CoBroker_lk__c',       panel.CoBroker_lk__c);
            items.put('PlacingSharingPct__c',        panel.PlacingSharingPct__c);
            items.put('PlacingTPPAdminFeePct__c',    panel.PlacingTPPAdminFeePct__c);
            items.put('PlacingSettlementType__c',    panel.PlacingSettlementType__c);

            items.put('LKCoBrokingSharing_is__c', panel.LKCoBrokingSharing_is__c);

            items.put('LKReBrkge__c',         panel.LKReBrkge__c);
            items.put('ProducingTPPBrkg__c',  panel.ProducingTPPBrkg__c);
            items.put('PlacingTPPBrkge__c',   panel.PlacingTPPBrkge__c);
            items.put('LKTPPBrkge__c',        panel.LKTPPBrkge__c);
            items.put('LKAdminFee__c',        panel.LKAdminFee__c);

            items.put('NetRI__c',             panel.NetRI__c);
            items.put('NetProducingTPP__c',   panel.NetProducingTPP__c);
            items.put('NetPlacingTPP__c',     panel.NetPlacingTPP__c);
            items.put('NetLKTPP__c',          panel.NetLKTPP__c);

            items.put('ClmNetRI__c',                panel.ClmNetRI__c);
            items.put('ClmNetToPlacingTPP__c',      panel.ClmNetToPlacingTPP__c);
            items.put('ClmNetToPlacingTPPLK__c',    panel.ClmNetToPlacingTPPLK__c);

            items.put('ProducingSharingPct__c',  panel.ProducingSharingPct__c);
            items.put('ProducingTPPAdminFeePct__c', panel.ProducingTPPAdminFeePct__c);
            items.put('CobrokingType__c',     panel.CobrokingType__c);
            items.put('NetProducingCobrker__c', panel.NetProducingCobrker__c);
            items.put('LKPlacingTPPBrkg__c',  panel.LKPlacingTPPBrkg__c);
            items.put('ToProducingAdminFee__c', panel.ToProducingAdminFee__c);
            items.put('ToLKAdminFee__c',      panel.ToLKAdminFee__c);
            items.put('LKNetPlacingTPP__c',   panel.LKNetPlacingTPP__c);
            items.put('LKPlacingSharingPct__c',   panel.LKPlacingSharingPct__c);

            items.put('RIContact_lk__c',      panel.RIContact_lk__c);
            items.put('CoBrokerContact_lk__c',panel.CoBrokerContact_lk__c);

            items.put('Others__c',            panel.Others__c);
            items.put('Subjectivity__c',      panel.Subjectivity__c);
            items.put('NetToUW__c',           panel.NetToUW__c);

            this.values = items;
        }
    }

    private static String mapSfTypeToCellType(DescribeFieldResult describeFieldResult) {
        Schema.DisplayType displayType = describeFieldResult.getType();
        if (displayType == Schema.DisplayType.DATE) return 'd';
        if (displayType == Schema.DisplayType.DATETIME) return 'dt';
        if (displayType == Schema.DisplayType.CURRENCY || displayType == Schema.DisplayType.DOUBLE || displayType == Schema.DisplayType.INTEGER || displayType == Schema.DisplayType.PERCENT) return 'num';
        if (displayType == Schema.DisplayType.PICKLIST) return 'picklist';
        if (displayType == Schema.DisplayType.MULTIPICKLIST) return 'multipicklist';
        if (displayType == Schema.DisplayType.BOOLEAN) return 'checkbox';
        if (displayType == Schema.DisplayType.REFERENCE) return 'lookup';
        if (displayType == Schema.DisplayType.TEXTAREA) {
            return describeFieldResult.isHtmlFormatted() ? 'richtext' : 'textarea';
        }
        return 'text';
    }
}