force-app/main/default/objects/Account/fields/CompanyNameEng__c.field-meta.xml
<CustomField>
    <fullName>CompanyNameEng__c</fullName>
    <description>기존 Dynamics 참조</description>
    <inlineHelpText>거래처명_영문</inlineHelpText>
    <label>Company Name(Eng)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/LastPLA_is__c.field-meta.xml
<CustomField>
    <fullName>LastPLA_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Last PLA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim/fields/LKRefNo_fm__c.field-meta.xml
<CustomField>
    <fullName>LKRefNo_fm__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Placement_lk__c,  Placement_lk__r.LKRefNoh__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LK Ref. No.</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claim/fields/ParentClaim_lk__c.field-meta.xml
<CustomField>
    <fullName>ParentClaim_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Claim</label>
    <referenceTo>Claim</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim/fields/SettlementCurrency__c.field-meta.xml
<CustomField>
    <fullName>SettlementCurrency__c</fullName>
    <label>Settlement Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/CLM_Allocation__c.object-meta.xml
<CustomObject>
    <label>Claim Allocation</label>
    <nameField>
        <label>Claim Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_Allocation__c/fields/Claim_md__c.field-meta.xml
<CustomField>
    <fullName>Claim_md__c</fullName>
    <label>SOC/PLA No.</label>
    <referenceTo>Claim</referenceTo>
    <relationshipLabel>Claim Allocation</relationshipLabel>
    <relationshipName>ClaimAllocationByClaim</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/FacilityParticipant_lk__c.field-meta.xml
<CustomField>
    <fullName>FacilityParticipant_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Participant</label>
    <referenceTo>COM_FacilityParticipant__c</referenceTo>
    <relationshipLabel>Claim Allocation</relationshipLabel>
    <relationshipName>Claim_Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/TotalAmtForRISettled__c.field-meta.xml
<CustomField>
    <fullName>TotalAmtForRISettled__c</fullName>
    <label>Total Amount (for Reinsurer) Settled</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDX__c/COM_FacilityBDX__c.object-meta.xml
<CustomObject>
    <description>SOA (Statement of Account) Master Object</description>
    <label>Facility BDX</label>
    <nameField>
        <label>Facility BDX</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility BDX</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/COM_FacilityBDX__c/fields/BDXType__c.field-meta.xml
<CustomField>
    <fullName>BDXType__c</fullName>
    <label>BDX Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit Note</fullName>
            </value>
            <value>
                <fullName>SOA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/COM_FacilityBDX__c/fields/FacilityParticipant_lk__c.field-meta.xml
<CustomField>
    <fullName>FacilityParticipant_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account (Issue to)</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3 AND ((4 AND 5) OR (6 AND 7))</booleanFilter>
        <filterItems>
            <field>$Source.Facility_lk__c</field>
            <operation>equals</operation>
            <valueField>COM_FacilityParticipant__c.Facility_lk__c</valueField>
        </filterItems>
        <filterItems>
            <field>COM_FacilityParticipant__c.BillingCycle__c</field>
            <operation>notEqual</operation>
            <value>Separate</value>
        </filterItems>
        <filterItems>
            <field>COM_FacilityParticipant__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>COM_FacilityParticipant__c.CedantReinsurer_fm__c</field>
            <operation>equals</operation>
            <value>Cedant</value>
        </filterItems>
        <filterItems>
            <field>$Source.BDXType__c</field>
            <operation>equals</operation>
            <value>Debit Note</value>
        </filterItems>
        <filterItems>
            <field>COM_FacilityParticipant__c.CedantReinsurer_fm__c</field>
            <operation>equals</operation>
            <value>Reinsurer</value>
        </filterItems>
        <filterItems>
            <field>$Source.BDXType__c</field>
            <operation>equals</operation>
            <value>SOA</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>COM_FacilityParticipant__c</referenceTo>
    <relationshipLabel>Facility BDX</relationshipLabel>
    <relationshipName>SOAByFacilityParticipant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDX__c/fields/IssueFrom__c.field-meta.xml
<CustomField>
    <fullName>IssueFrom__c</fullName>
    <label>BDX Period (From)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDX__c/fields/IssueTo__c.field-meta.xml
<CustomField>
    <fullName>IssueTo__c</fullName>
    <label>BDX Period (To)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/COM_FacilityBDXLineItem__c.object-meta.xml
<CustomObject>
    <description>Facility BDX Line Items</description>
    <label>Facility BDX Line Item</label>
    <nameField>
        <displayFormat>FBLI_{00000000}</displayFormat>
        <label>Facility BDX Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility BDX Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/Claim_lk__c.field-meta.xml
<CustomField>
    <fullName>Claim_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claim</label>
    <referenceTo>Claim</referenceTo>
    <relationshipName>SOA_LineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/FacilityBDX_md__c.field-meta.xml
<CustomField>
    <fullName>FacilityBDX_md__c</fullName>
    <label>Facility BDX</label>
    <referenceTo>COM_FacilityBDX__c</referenceTo>
    <relationshipLabel>Facility BDX Line Items</relationshipLabel>
    <relationshipName>SOA_LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/LKRefNo_fm__c.field-meta.xml
<CustomField>
    <fullName>LKRefNo_fm__c</fullName>
    <formula>Placement_lk__r.LKRefNoh__c</formula>
    <label>LK Ref No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/NetShare_fm__c.field-meta.xml
<CustomField>
    <fullName>NetShare_fm__c</fullName>
    <formula>Note_lk__r.NetToLKPrem__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/OriginAmount_fm__c.field-meta.xml
<CustomField>
    <fullName>OriginAmount_fm__c</fullName>
    <formula>Note_lk__r.NoteAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Origin Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/OriginCurrency_fm__c.field-meta.xml
<CustomField>
    <fullName>OriginCurrency_fm__c</fullName>
    <formula>TEXT(Note_lk__r.OriginCurrency__c)</formula>
    <label>Origin Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/PremOnLKShare_fm__c.field-meta.xml
<CustomField>
    <fullName>PremOnLKShare_fm__c</fullName>
    <formula>GrossPrem_fm__c * TotalOrderPct_fm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prem on LK Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/TotalDeduction_fm__c.field-meta.xml
<CustomField>
    <fullName>TotalDeduction_fm__c</fullName>
    <formula>Note_lk__r.TotalDeductionAmt_fm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Deductions</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/fields/TotalOrderPct_fm__c.field-meta.xml
<CustomField>
    <fullName>TotalOrderPct_fm__c</fullName>
    <formula>Placement_lk__r.TotalOrderPct__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Order (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COM_FacilityBDXLineItem__c/recordTypes/Premium.recordType-meta.xml
<RecordType>
    <fullName>Premium</fullName>
    <active>true</active>
    <label>Premium</label>
</RecordType>

force-app/main/default/objects/COM_FacilityParticipant__c/COM_FacilityParticipant__c.object-meta.xml
<CustomObject>
    <description>Facility별 참여사 정보 관리</description>
    <label>Facility Participant</label>
    <nameField>
        <label>Facility Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Participants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/COM_FacilityParticipant__c/fields/CedantAccount_lk__c.field-meta.xml
<CustomField>
    <fullName>CedantAccount_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account 중 Cadent 지정(룩업필터 지정 필요)</description>
    <label>Cedant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.isInsurerAcc__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facility Participants (Cedant)</relationshipLabel>
    <relationshipName>FacilityParticipantsByCedant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COM_FacilityParticipant__c/fields/PeriodFrom__c.field-meta.xml
<CustomField>
    <fullName>PeriodFrom__c</fullName>
    <label>Period From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/COM_FacilityParticipant__c/fields/PeriodTo__c.field-meta.xml
<CustomField>
    <fullName>PeriodTo__c</fullName>
    <label>Period To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/COM_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>CNY</fullName>
    </customValue>
    <customValue>
        <fullName>RMB</fullName>
    </customValue>
    <customValue>
        <fullName>STG</fullName>
    </customValue>
    <masterLabel>[COM] Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FacilityBDXDocGen.cls
/**********************************************************************************
 * @filename       : FacilityBDXDocGen.cls
 * @projectname   : LK보험중개_신규계약관리시스템 구축
 * @author        : i2max
 * @date          : 2026-03-24 (화)
 * @group         :
 * @group-content :
 * @description   : Facility BDX 문서 생성을 위한 Remote Action 용 Class
 *                  OmniScript => FacilityBDX_SOA_DocGen / FacilityBDX_DebitNote_DocGen 에서 사용
 * @test-class    : FacilityBDXDocGen_ts.cls
 * @reference     :
 * @copyright     :
 * @modification  Log
 * ===================================================================
 * ver   date            author           description
 * ===================================================================
 * 1.0   2026-03-24      i2max            Create
**********************************************************************************/

public with sharing class FacilityBDXDocGen implements Callable {

    @TestVisible
    private static List<Map<String, Object>> testRefItems;
    @TestVisible
    private static List<Map<String, Object>> testShareItems;
    @TestVisible
    private static List<Map<String, Object>> testCurrencyItems;
    @TestVisible
    private static List<Map<String, Object>> testLossRows;
    @TestVisible
    private static List<Map<String, Object>> testAllocationAggRows;

    // Type 구분
    /**
     * @description BDX 타입 조회
     * @param recordId COM_FacilityBDX__c Id
     * @return BDXType__c 값 (없으면 빈 문자열)
     */
    @AuraEnabled(Cacheable=true)
    public static String getBDXType(Id recordId) {
        try {
            COM_FacilityBDX__c bdx = [
                    SELECT BDXType__c
                    FROM COM_FacilityBDX__c
                    WHERE Id = :recordId
                    LIMIT 1
            ];

            return (bdx.BDXType__c != null) ? bdx.BDXType__c : '';
        } catch (Exception e) {
            throw new AuraHandledException('BDX 타입을 가져오는 중 오류 발생: ' + e.getMessage());
        }
    }

    /**
     * @description 해당 Facility BDX 에 연결된 Line Item 존재 여부 확인
     * @param recordId COM_FacilityBDX__c Id
     * @return Line Item 이 1건 이상 존재하면 true, 없으면 false
     */
    @AuraEnabled(Cacheable=true)
    public static Boolean checkLineItemsExist(Id recordId) {
        try {
            // 해당 Facility BDX에 연결된 Line Item 있는지 Count
            Integer count = [
                    SELECT COUNT()
                    FROM COM_FacilityBDXLineItem__c
                    WHERE FacilityBDX_md__c = :recordId
                    LIMIT 1
            ];
            return count > 0;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @description Callable 인터페이스 구현 메서드.
     *              action = 'getPeriodData' 인 경우 기간 정보, 참조번호, 공유율, Cedant 명,
     *              문서 생성일, Currency 별 테이블 데이터를 output/input 에 세팅한다.
     * @param action 실행할 액션 명 (현재 'getPeriodData' 지원)
     * @param args   input / output / options 맵을 포함하는 인자 맵
     * @return 처리 완료 여부 (true)
     */
    public Object call (String action, Map<String, Object> args) {
        Map<String, Object> input = (Map<String, Object>)args.get('input');
        Map<String, Object> output = (Map<String, Object>)args.get('output');
        Map<String, Object> options = (Map<String, Object>)args.get('options');

        Id facilityId = (Id) options.get('facilityId');
        if (facilityId == null) {
            facilityId = (Id) input.get('ContextId');
        }

        if (action == 'getPeriodData') {
            if (facilityId != null) {
                // 날짜 데이터 포맷
                Map<String, String> periodData = getPeriodData(facilityId);
                output.putAll(periodData);

                // LK Ref
                String refDisplay = getReferenceDisplay(facilityId);
                output.put('ReferenceDisplay', refDisplay);

                // LK Share
                String shareDisplay = getShareDisplay(facilityId);
                output.put('ShareDisplay', shareDisplay);

                // To Cedant 명
                String cedantName = getCedantName(facilityId);
                output.put('CedantCompanyName', cedantName);

                // 문서 생성일자
                String todayDate = getTodayDate();
                output.put('TodayDate', todayDate);

                // Currency 별 테이블 생성
                List<Map<String, Object>> currencyTables = getCurrencyTableData(facilityId);
                //output.put('CurrencyTables', currencyTables);
                // Outstanding Losses
                List<Map<String, Object>> lossData = getOutstandingLossData(facilityId);
                //output.put('OutstandingLosses', outstandingLosses);

                // Currency + OutstandingLoss
                for (Map<String, Object> tableRow : currencyTables) {
                    String tableCurr = (String)tableRow.get('Currency');
                    tableRow.put('OutstandingLoss', '0'); // 기본값 설정

                    for (Map<String, Object> lossRow : lossData) {
                        // 통화가 일치하면 금액을 꽂아줌
                        if (tableCurr != null && tableCurr.equals(lossRow.get('Currency'))) {
                            tableRow.put('OutstandingLoss', lossRow.get('Amount'));
                            break;
                        }
                    }
                }

                output.put('CurrencyTables', currencyTables);

                if (input != null) {
                    input.putAll(periodData);
                    input.put('ReferenceDisplay', refDisplay);
                    input.put('ShareDisplay', shareDisplay);
                    input.put('CurrencyTables', currencyTables);
                    input.put('CedantCompanyName', cedantName);
                    input.put('TodayDate', todayDate);
                }
            }
        }

        System.debug('### FINAL OUTPUT => ' + JSON.serializePretty(output));
        return true;
    }

    /**
     * @description Facility BDX 에 연결된 Cedant 회사명 조회
     * @param facilityId COM_FacilityBDX__c Id
     * @return Cedant Account 의 CompanyNameEng__c 값 (없으면 빈 문자열)
     */
    private static String getCedantName(Id facilityId) {
        List<COM_FacilityBDX__c> bdxList = [
                SELECT FacilityParticipant_lk__r.CedantAccount_lk__r.CompanyNameEng__c
                FROM COM_FacilityBDX__c
                WHERE Id = :facilityId
                LIMIT 1
        ];

        if (bdxList.isEmpty()) return '';

        String name = bdxList[0].FacilityParticipant_lk__r.CedantAccount_lk__r.CompanyNameEng__c;
        return (name != null) ? name : '';
    }

    /**
     * @description 오늘 날짜를 '1st January 2026' 형식의 영문 날짜 문자열로 반환
     * @return 포맷된 오늘 날짜 문자열
     */
    private static String getTodayDate() {
        Date today = Date.today();
        Integer day = today.day();

        String suffix = getDaySuffix(day);

        // 월/년도 포맷
        String monthYear = Datetime.newInstance(today.year(), today.month(), today.day()).format('MMMM yyyy');
        return String.valueOf(day) + suffix + ' ' + monthYear;
    }

    /**
     * @description 날짜의 일(day) 값에 해당하는 영어 서수 접미사 반환 (st / nd / rd / th)
     * @param day 일(day) 숫자
     * @return 서수 접미사 문자열
     */
    @TestVisible
    private static String getDaySuffix(Integer day) {
        String suffix = 'th';

        if (day < 11 || day > 13) {
            Integer lastDigit = Math.mod(day, 10);
            if (lastDigit == 1) {
                suffix = 'st';
            } else if (lastDigit == 2) {
                suffix = 'nd';
            } else if (lastDigit == 3) {
                suffix = 'rd';
            }
        }

        return suffix;
    }


    /**
     * @description Facility BDX 의 Issue Period 및 연결된 Participant 의 Period From/To 날짜를
     *              영문 포맷으로 변환하여 맵으로 반환
     * @param facilityId COM_FacilityBDX__c Id
     * @return FormattedIssuePeriod / FormattedFromDate / FormattedToDate 키를 포함한 맵
     */
    private static Map<String, String> getPeriodData(Id facilityId) {
        Map<String, String> resultMap = new Map<String, String>();

        List<COM_FacilityBDX__c> bdxList = [
                SELECT FacilityParticipant_lk__c, IssueFrom__c, IssueTo__c
                FROM COM_FacilityBDX__c
                WHERE Id = :facilityId
                LIMIT 1
        ];

        if (bdxList.isEmpty()) {
            return resultMap;
        }

        COM_FacilityBDX__c bdx = bdxList[0];

        // Issue Period 포맷
        if (bdx.IssueFrom__c != null && bdx.IssueTo__c != null) {
            String issueFromStr = Datetime.newInstance(bdx.IssueFrom__c, Time.newInstance(0,0,0,0)).format('dd MMMM yyyy');
            String issueToStr = Datetime.newInstance(bdx.IssueTo__c, Time.newInstance(0,0,0,0)).format('dd MMMM yyyy');

            String combinedIssuePeriod = '(' + issueFromStr + ' - ' + issueToStr + ')';
            resultMap.put('FormattedIssuePeriod', combinedIssuePeriod);
        }

        if (bdx.FacilityParticipant_lk__c != null) {
            List<COM_FacilityParticipant__c> pList = [
                    SELECT PeriodFrom__c, PeriodTo__c
                    FROM COM_FacilityParticipant__c
                    WHERE Id = :bdx.FacilityParticipant_lk__c
                    LIMIT 1
            ];

            if (!pList.isEmpty()) {
                COM_FacilityParticipant__c p = pList[0];

                String formattedFrom = (p.PeriodFrom__c != null) ?
                        Datetime.newInstance(p.PeriodFrom__c, Time.newInstance(0,0,0,0)).format('dd MMMM yyyy') : '';

                String formattedTo = (p.PeriodTo__c != null) ?
                        Datetime.newInstance(p.PeriodTo__c, Time.newInstance(0,0,0,0)).format('dd MMMM yyyy') : '';

                resultMap.put('FormattedFromDate', formattedFrom);
                resultMap.put('FormattedToDate', formattedTo);
            }
        }

        return resultMap;
    }

    /**
     * @description LK Ref No. 표시 문자열 조회.
     *              단일 값이면 그대로, 복수 값이면 '{값} and others' 형식으로 반환
     * @param facilityId COM_FacilityBDX__c Id
     * @return LK Ref No. 표시 문자열
     */
    private static String getReferenceDisplay(Id facilityId) {
        if (Test.isRunningTest() && testRefItems != null) {
            return buildReferenceDisplay(testRefItems);
        }

        List<COM_FacilityBDXLineItem__c> items = [
                SELECT LKRefNo_fm__c
                FROM COM_FacilityBDXLineItem__c
                WHERE FacilityBDX_md__c = :facilityId
                ORDER BY NetShare_fm__c DESC, CreatedDate ASC
        ];

        List<Map<String, Object>> mapItems = new List<Map<String, Object>>();
        for (COM_FacilityBDXLineItem__c item : items) {
            mapItems.add(new Map<String, Object>{ 'LKRefNo_fm__c' => item.LKRefNo_fm__c });
        }
        return buildReferenceDisplay(mapItems);
    }

    /**
     * @description Line Item 목록으로 LK Ref No. 표시 문자열 생성
     * @param items LKRefNo_fm__c 키를 포함한 맵 리스트
     * @return LK Ref No. 표시 문자열
     */
    private static String buildReferenceDisplay(List<Map<String, Object>> items) {
        if (items == null || items.isEmpty()) return '';

        Set<String> uniqueRefs = new Set<String>();
        for (Map<String, Object> item : items) {
            String ref = (String) item.get('LKRefNo_fm__c');
            if (ref != null) uniqueRefs.add(ref);
        }

        String topValue = (String) items[0].get('LKRefNo_fm__c');
        return uniqueRefs.size() <= 1 ? topValue : topValue + ' and others';
    }

    /**
     * @description LK Share(%) 표시 문자열 조회.
     *              단일 값이면 '{값}%', 복수 값이면 '{값}% and others' 형식으로 반환
     * @param facilityId COM_FacilityBDX__c Id
     * @return Share 표시 문자열
     */
    private static String getShareDisplay(Id facilityId) {
        if (Test.isRunningTest() && testShareItems != null) {
            return buildShareDisplay(testShareItems);
        }

        List<COM_FacilityBDXLineItem__c> items = [
                SELECT TotalOrderPct_fm__c
                FROM COM_FacilityBDXLineItem__c
                WHERE FacilityBDX_md__c = :facilityId
                ORDER BY TotalOrderPct_fm__c DESC, CreatedDate ASC
        ];

        List<Map<String, Object>> mapItems = new List<Map<String, Object>>();
        for (COM_FacilityBDXLineItem__c item : items) {
            mapItems.add(new Map<String, Object>{ 'TotalOrderPct_fm__c' => item.TotalOrderPct_fm__c });
        }
        return buildShareDisplay(mapItems);
    }

    /**
     * @description Line Item 목록으로 Share 표시 문자열 생성
     * @param items TotalOrderPct_fm__c 키를 포함한 맵 리스트
     * @return Share 표시 문자열
     */
    private static String buildShareDisplay(List<Map<String, Object>> items) {
        if (items == null || items.isEmpty()) return '';

        Set<Decimal> uniqueShares = new Set<Decimal>();
        for (Map<String, Object> item : items) {
            Decimal share = toDecimal(item.get('TotalOrderPct_fm__c'));
            if (share != null) uniqueShares.add(share);
        }

        String topValue = String.valueOf(toDecimal(items[0].get('TotalOrderPct_fm__c')));
        return uniqueShares.size() <= 1 ? topValue + '%' : topValue + '% and others';
    }

    /**
     * @description Currency 별 Premium/Claim 집계 테이블 데이터 생성.
     *              A(PremOnLKShare), B(TotalDeduction), C(A-B), D(OriginAmount of Claim), E(C-D) 컬럼을 포함한다.
     * @param facilityId COM_FacilityBDX__c Id
     * @return Currency 별 집계 맵 리스트 (Currency / SumA~SumE / OutstandingLoss 키 포함)
     */
    private static List<Map<String, Object>> getCurrencyTableData(Id facilityId) {
        List<Map<String, Object>> tableList = new List<Map<String, Object>>();

        Map<String, Map<String, Decimal>> currencyMap = new Map<String, Map<String, Decimal>>();
        Set<String> premiumCurrencies = new Set<String>();

        List<Map<String, Object>> sourceItems = new List<Map<String, Object>>();
        if (Test.isRunningTest() && testCurrencyItems != null) {
            sourceItems = testCurrencyItems;
        } else {
            List<COM_FacilityBDXLineItem__c> items = [
                    SELECT OriginCurrency_fm__c, PremOnLKShare_fm__c, TotalDeduction_fm__c, OriginAmount_fm__c, Claim_lk__c
                    FROM COM_FacilityBDXLineItem__c
                    WHERE FacilityBDX_md__c = :facilityId
            ];
            for (COM_FacilityBDXLineItem__c item : items) {
                sourceItems.add(new Map<String, Object>{
                        'OriginCurrency_fm__c' => item.OriginCurrency_fm__c,
                        'PremOnLKShare_fm__c' => item.PremOnLKShare_fm__c,
                        'TotalDeduction_fm__c' => item.TotalDeduction_fm__c,
                        'OriginAmount_fm__c' => item.OriginAmount_fm__c,
                        'Claim_lk__c' => item.Claim_lk__c
                });
            }
        }

        for (Map<String, Object> item : sourceItems) {
            String curr = (String) item.get('OriginCurrency_fm__c');
            if (String.isBlank(curr)) curr = 'N/A';

            if (!currencyMap.containsKey(curr)) {
                currencyMap.put(curr, new Map<String, Decimal>{ 'A' => 0, 'B' => 0, 'D' => 0, 'OL' => 0 });
            }

            Map<String, Decimal> sums = currencyMap.get(curr);
            Id claimId = (Id) item.get('Claim_lk__c');

            if (claimId == null) {
                premiumCurrencies.add(curr);
                Decimal a = toDecimal(item.get('PremOnLKShare_fm__c'));
                Decimal b = toDecimal(item.get('TotalDeduction_fm__c'));
                sums.put('A', sums.get('A') + (a != null ? a : 0));
                sums.put('B', sums.get('B') + (b != null ? b : 0));
            } else {
                Decimal d = toDecimal(item.get('OriginAmount_fm__c'));
                sums.put('D', sums.get('D') + (d != null ? d : 0));
            }
        }

        // premiumCurrencies 기준으로 테이블 Row
        for (String curr : premiumCurrencies) {
            Map<String, Decimal> v = currencyMap.get(curr);

            Decimal aVal = v.get('A');
            Decimal bVal = v.get('B');
            Decimal cVal = aVal - bVal;         // C = A - B
            Decimal dVal = v.get('D');          // D = Claim != null 레코드의 OriginAmount_fm__c 합계
            Decimal eVal = cVal - dVal;         // E = C - D

            Map<String, Object> row = new Map<String, Object>();
            row.put('Currency', curr);
            row.put('SumA', formatNumber(aVal));
            row.put('SumB', formatNumber(bVal));
            row.put('SumC', formatNumber(cVal));
            row.put('SumD', formatNumber(dVal));
            row.put('SumE', formatNumber(eVal));

            tableList.add(row);
        }

        return tableList;
    }

    /**
     * @description Decimal 값을 천 단위 구분 기호가 포함된 정수 문자열로 포맷
     * @param d 포맷할 Decimal 값
     * @return 포맷된 숫자 문자열
     */
    private static String formatNumber(Decimal d) {
        return d.setScale(0).format();
    }

    /**
     * @description Outstanding Loss 데이터 조회.
     *              BDX Line Item 에 연결된 Claim 의 Parent Claim 을 기준으로
     *              CLM_Allocation__c 의 TotalAmtForRISettled__c 를 Currency 별로 집계하여 반환
     * @param facilityId COM_FacilityBDX__c Id
     * @return Currency / Amount 키를 포함한 집계 맵 리스트
     */
    private static List<Map<String, Object>> getOutstandingLossData(Id facilityId) {

        if (Test.isRunningTest() && testLossRows != null) {
            return testLossRows;
        }

        if (Test.isRunningTest() && testAllocationAggRows != null) {
            List<Map<String, Object>> mockedResult = new List<Map<String, Object>>();
            for (Map<String, Object> ar : testAllocationAggRows) {
                Map<String, Object> row = new Map<String, Object>();
                row.put('Currency', ar.get('curr') != null ? (String) ar.get('curr') : 'N/A');
                row.put('Amount', formatNumber(toDecimal(ar.get('total'))));
                mockedResult.add(row);
            }
            return mockedResult;
        }

        List<Map<String, Object>> resultList = new List<Map<String, Object>>();
        Set<Id> parentClaimIds = new Set<Id>();

        // BDX에 연결된 Line Item들의 Parent Claim ID
        for (COM_FacilityBDXLineItem__c item : [
                SELECT Claim_lk__r.ParentClaim_lk__c
                FROM COM_FacilityBDXLineItem__c
                WHERE FacilityBDX_md__c = :facilityId
                AND Claim_lk__c != NULL
        ]) {
            parentClaimIds.add(item.Claim_lk__r.ParentClaim_lk__c);
        }

        if (parentClaimIds.isEmpty()) return resultList;

        // Parent를 공유하는 자식들의 Allocation 합산
        for (AggregateResult ar : [
                SELECT SettlementCurrency__c curr, SUM(TotalAmtForRISettled__c) total
                FROM CLM_Allocation__c
                WHERE Claim_md__c IN (
                        SELECT Id FROM Claim
                        WHERE ParentClaim_lk__c IN :parentClaimIds
                        AND LastPLA_is__c = TRUE
                )
                GROUP BY SettlementCurrency__c
        ]) {
            Map<String, Object> row = new Map<String, Object>();
            row.put('Currency', ar.get('curr') != null ? (String)ar.get('curr') : 'N/A');
            row.put('Amount', formatNumber((Decimal)ar.get('total')));
            resultList.add(row);
        }

        return resultList;
    }

    /**
     * @description Object 타입 값을 Decimal 로 변환 (null 이면 null 반환)
     * @param raw 변환할 Object 값 (Decimal / Integer / Long / Double / String 지원)
     * @return 변환된 Decimal 값
     */
    private static Decimal toDecimal(Object raw) {
        if (raw == null) return null;
        if (raw instanceof Decimal) return (Decimal) raw;
        if (raw instanceof Integer) return Decimal.valueOf((Integer) raw);
        if (raw instanceof Long) return Decimal.valueOf((Long) raw);
        if (raw instanceof Double) return Decimal.valueOf((Double) raw);
        return Decimal.valueOf(String.valueOf(raw));
    }

}