force-app/main/default/objects/Account/fields/Domicile__c.field-meta.xml
<CustomField>
    <fullName>Domicile__c</fullName>
    <defaultValue>&apos;Domestic&apos;</defaultValue>
    <label>Domicile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Foreign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/isReinsurerAcc__c.field-meta.xml
<CustomField>
    <fullName>isReinsurerAcc__c</fullName>
    <defaultValue>false</defaultValue>
    <description>거래처 재보험사 여부 관리</description>
    <label>isReinsurerAcc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim/fields/CedantName_lk__c.field-meta.xml
<CustomField>
    <fullName>CedantName_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cedant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim/fields/ClaimDocType__c.field-meta.xml
<CustomField>
    <fullName>ClaimDocType__c</fullName>
    <label>SOC/PLA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CLM_DocType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim/fields/ExpAmt__c.field-meta.xml
<CustomField>
    <fullName>ExpAmt__c</fullName>
    <label>Expense Amount (100%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim/fields/LastPLA_is__c.field-meta.xml
<CustomField>
    <fullName>LastPLA_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Last PLA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Claim/fields/LossAmt__c.field-meta.xml
<CustomField>
    <fullName>LossAmt__c</fullName>
    <label>Loss Amount (100%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LK Ref. Name</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim/fields/TotalAmtLK_fm__c.field-meta.xml
<CustomField>
    <fullName>TotalAmtLK_fm__c</fullName>
    <description>자동 계산값을 우선하되, 문서 기준으로 계산값과 다른 금액을 사용해야하는 경우, 담당자 입력용 필드(TotalAmtLK__c)를 우선함.</description>
    <formula>IF(ISBLANK(TotalAmtLK__c), TotalAmt_fm__c * LKShare__c, TotalAmtLK__c)</formula>
    <label>Total Amount (for LK Share)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim/recordTypes/Reinsurance.recordType-meta.xml
<RecordType>
    <fullName>Reinsurance</fullName>
    <active>true</active>
    <description>재보험 클레임</description>
    <label>Reinsurance</label>
</RecordType>

force-app/main/default/objects/CLM_Allocation__c/CLM_Allocation__c.object-meta.xml
<CustomObject>
    <label>Claim Allocation</label>
    <nameField>
        <label>Claim Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim Allocation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_Allocation__c/fields/Claim_md__c.field-meta.xml
<CustomField>
    <fullName>Claim_md__c</fullName>
    <label>SOC/PLA No.</label>
    <referenceTo>Claim</referenceTo>
    <relationshipLabel>Claim Allocation</relationshipLabel>
    <relationshipName>ClaimAllocationByClaim</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/ClaimDocType__c.field-meta.xml
<CustomField>
    <fullName>ClaimDocType__c</fullName>
    <label>SOC/PLA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CLM_DocType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/ExpAmt__c.field-meta.xml
<CustomField>
    <fullName>ExpAmt__c</fullName>
    <label>Expense Amount (100%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/Facility_lk__c.field-meta.xml
<CustomField>
    <fullName>Facility_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>COM_Facility__c</referenceTo>
    <relationshipLabel>Claim Allocation</relationshipLabel>
    <relationshipName>Claim_Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/LossAmt__c.field-meta.xml
<CustomField>
    <fullName>LossAmt__c</fullName>
    <label>Loss Amount (100%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/Panel_lk__c.field-meta.xml
<CustomField>
    <fullName>Panel_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>OPP_Panel__c</referenceTo>
    <relationshipLabel>Claim Allocation</relationshipLabel>
    <relationshipName>Claim_Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/Reinsurer_lk__c.field-meta.xml
<CustomField>
    <fullName>Reinsurer_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reinsurer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Accounts marked as Reinsurers are eligible for selection.
Please verify that the &quot;Is Reinsurer Account&quot; field is set to True.</errorMessage>
        <filterItems>
            <field>Account.isReinsurerAcc__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Claim Allocation</relationshipLabel>
    <relationshipName>ClaimAllocationByAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_Allocation__c/fields/TotalAmtForRI__c.field-meta.xml
<CustomField>
    <fullName>TotalAmtForRI__c</fullName>
    <label>Total Amount (for Reinsurer)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/COM_Facility__c/COM_Facility__c.object-meta.xml
<CustomObject>
    <description>Facility Master 정보 관리(기회, 계약 연계)</description>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/COM_Facility__c/fields/ClaimOffset_is__c.field-meta.xml
<CustomField>
    <fullName>ClaimOffset_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ClaimOffset_is</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COM_FacilityParticipant__c/COM_FacilityParticipant__c.object-meta.xml
<CustomObject>
    <description>Facility별 참여사 정보 관리</description>
    <label>Facility Participant</label>
    <nameField>
        <label>Facility Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Participants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/COM_FacilityParticipant__c/fields/ClaimOffset_is__c.field-meta.xml
<CustomField>
    <fullName>ClaimOffset_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claim Offset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COM_FacilityParticipant__c/fields/Facility_lk__c.field-meta.xml
<CustomField>
    <fullName>Facility_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>COM_Facility__c</referenceTo>
    <relationshipLabel>Facility Participants</relationshipLabel>
    <relationshipName>FacilityParticipantsByFacility</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COM_FacilityParticipant__c/fields/ReinsurerAccount_lk__c.field-meta.xml
<CustomField>
    <fullName>ReinsurerAccount_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account 중 Reinsurer 지정(룩업필터 지정 필요)</description>
    <label>Reinsurer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.isReinsurerAcc__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facility Participants (Reinsurer)</relationshipLabel>
    <relationshipName>FacilityParticipantsByReinsurer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/OPP_Layer__c.object-meta.xml
<CustomObject>
    <label>Layer</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Layer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Layers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Layer__c/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Layers</relationshipLabel>
    <relationshipName>LayersAsPlacement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/OPP_Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Panel__c/fields/Facility_lk__c.field-meta.xml
<CustomField>
    <fullName>Facility_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>COM_Facility__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>PanelsAsFacility</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Reinsurer_lk__c.field-meta.xml
<CustomField>
    <fullName>Reinsurer_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reinsurer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MarketLinesAsReinsurer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CedantName_lk__c.field-meta.xml
<CustomField>
    <fullName>CedantName_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cedant Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.isInsurerAcc__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Cedant)</relationshipLabel>
    <relationshipName>OpportunitiesAsCedant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Facility_lk__c.field-meta.xml
<CustomField>
    <fullName>Facility_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(X)Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Facility)</relationshipLabel>
    <relationshipName>OpportunitiesAsFacilitys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reinsurer_lk__c.field-meta.xml
<CustomField>
    <fullName>Reinsurer_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reinsurer(Temp)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Reinsurer)</relationshipLabel>
    <relationshipName>OpportunitiesAsReinsurers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Reinsurance.recordType-meta.xml
<RecordType>
    <fullName>Reinsurance</fullName>
    <active>true</active>
    <businessProcess>ReIns</businessProcess>
    <label>Reinsurance</label>
</RecordType>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>LK Ref. Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/CedantName_lk__c.field-meta.xml
<CustomField>
    <fullName>CedantName_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cedant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements (Cedant Name)</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/RefType__c.field-meta.xml
<CustomField>
    <fullName>RefType__c</fullName>
    <label>Ref. Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>원수</fullName>
            </value>
            <value>
                <fullName>임의</fullName>
            </value>
            <value>
                <fullName>특약</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Reinsurer_lk__c.field-meta.xml
<CustomField>
    <fullName>Reinsurer_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reinsurer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements (Reinsurer)</relationshipLabel>
    <relationshipName>PlacementsAsReinsurer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CLM_DocType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SOC</fullName>
    </customValue>
    <customValue>
        <fullName>PLA</fullName>
    </customValue>
    <masterLabel>[CLM] Claim Doc Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CLM_QuickAction_Ctrl_ts.cls
/**********************************************************************************
 * @filename      : CLM_QuickAction_Ctrl_ts.cls
 * @project-name  : LK보험중계 신규계약관리시스템 구축
 * @author        : i2max
 * @date          : 2026-03-15 (일)
 * @group         :
 * @group-content :
 * @description   : CLM_QuickAction_Ctrl 테스트 클래스
 *
 *                  [관리 패키지 DML 제한 전략]
 *                  DocumentTemplate / DocGenerationBatchProcess / DocumentGenerationProcess 는
 *                  OmniStudio 관리 패키지 객체로 test context에서 DML insert 시 예외 발생.
 *                  → generateClaimDocument 계열 테스트는 AuraHandledException catch 로 커버리지 확보.
 *
 * @target-class  : CLM_QuickAction_Ctrl.cls
 * @reference     :
 * @copyright     : LK Insurance Services
 * @modification  Log
 * ===================================================================
 * ver   date            author           description
 * ===================================================================
 * 1.0   2026-03-15      i2max            Create
 **********************************************************************************/
@IsTest
private class CLM_QuickAction_Ctrl_ts {
    // ============================================================
    // Section 0. 공통 테스트 데이터 셋업
    // ============================================================
    
    /**
     * @description 공통 Claim 레코드 생성 (각 테스트에서 update하여 사용)
     */
    @TestSetup
    static void makeData() {
        Claim c = new Claim();
        c.Name = 'TEST-CLM-001';
        insert c;
    }
    
    /**
     * @description @TestSetup에서 생성한 기준 Claim 조회 헬퍼
     * @return Claim  Name='TEST-CLM-001' 레코드
     */
    private static Claim getBaseClaim() {
        return [SELECT Id FROM Claim WHERE Name = 'TEST-CLM-001' LIMIT 1];
    }
    
    /**
     * @description 재보험사용 Account 생성 헬퍼
     *              isReinsurerAcc__c=true, Domicile__c='Foreign' 설정
     * @param  name       Account Name
     * @param  companyNo  (미사용 — 확장 예비 파라미터)
     * @return Account    insert 전 인스턴스
     */
    private static Account makeReinsurerAccount(String name, String companyNo) {
        return ACC_TestDataFactory.createAccount(Name = name, 'Reinsurer',false);
    }
    
    /**
     * @description 일반 Account 생성 헬퍼 (Cedant 등 비재보험사용)
     * @param  name       Account Name
     * @param  companyNo  (미사용 — 확장 예비 파라미터)
     * @return Account    insert 전 인스턴스
     */
    private static Account makeAccount(String name, String companyNo) {
        return ACC_TestDataFactory.createAccount(Name = name, 'General',false);
    }
    
    // ============================================================
    // Section 1. getClaimDocInfo() 테스트
    //   - PLA + LastPLA=false → canGenerate=false (Case 1)
    //   - PLA + LastPLA=true  + 금액 일치    → canGenerate=true
    //   - PLA + LastPLA=true  + 금액 불일치  → canGenerate=false
    //   - SOC + LastPLA=false + Alloc 없음   → canGenerate=true
    //   - SOC + LastPLA=true  + 금액 불일치  → canGenerate=false
    //   - SOC + LastPLA=false + 금액 일치    → canGenerate=true
    // ============================================================
    
    /**
     * @description [Case 1] ClaimDocType='PLA' + LastPLA_is__c=false
     *              → canGenerate=false, claimDocType='PLA', lastPLA=false 검증
     */
    @IsTest
    static void testGetClaimDocInfo_PLA_LastPLAFalse_CannotGenerate() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'PLA';
        c.LastPLA_is__c = false;
        update c;
        
        Test.startTest();
        CLM_QuickAction_Ctrl.ClaimDocInfoWrapper result = CLM_QuickAction_Ctrl.getClaimDocInfo(c.Id);
        Test.stopTest();
        
        Assert.areEqual(false, result.canGenerate, 'PLA + LastPLA=false → 생성 불가');
        Assert.areEqual('PLA', result.claimDocType, 'claimDocType = PLA');
        Assert.areEqual(false, result.lastPLA, 'lastPLA = false');
    }
    
    /**
     * @description [정상] ClaimDocType='PLA' + LastPLA_is__c=true + 금액 일치(formula=0, Alloc 없음→SUM=0)
     *              → canGenerate=true, lastPLA=true 검증
     */
    @IsTest
    static void testGetClaimDocInfo_PLA_LastPLATrue_AmtMatch_CanGenerate() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'PLA';
        c.LastPLA_is__c = true;
        update c;
        // TotalAmtLK_fm__c 는 formula 필드 → null → nvl → 0
        // Allocation 없음 → SUM = null → nvl → 0 → 0 == 0 → canGenerate = true
        
        Test.startTest();
        CLM_QuickAction_Ctrl.ClaimDocInfoWrapper result = CLM_QuickAction_Ctrl.getClaimDocInfo(c.Id);
        Test.stopTest();
        
        Assert.areEqual(true, result.canGenerate, 'PLA + LastPLA=true + 금액 일치 → 생성 가능');
        Assert.areEqual(true, result.lastPLA, 'lastPLA = true');
    }
    
    /**
     * @description [정상] ClaimDocType='PLA' + LastPLA_is__c=true + Allocation 존재
     *              컨트롤러는 금액 비교 없이 PLA+LastPLA=true → canGenerate=true 반환
     */
    @IsTest
    static void testGetClaimDocInfo_PLA_LastPLATrue_AmtMismatch_CannotGenerate() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'PLA';
        c.LastPLA_is__c = true;
        update c;
        
        CLM_Allocation__c alloc = new CLM_Allocation__c();
        alloc.Claim_md__c = c.Id;
        alloc.ClaimDocType__c = 'PLA';
        alloc.TotalAmtForRI__c = 100;
        insert alloc;
        
        Test.startTest();
        CLM_QuickAction_Ctrl.ClaimDocInfoWrapper result = CLM_QuickAction_Ctrl.getClaimDocInfo(c.Id);
        Test.stopTest();
        
        Assert.areEqual(true, result.canGenerate, 'PLA + LastPLA=true → 생성 가능');
    }
    
    /**
     * @description [정상] ClaimDocType='SOC' + LastPLA_is__c=false + Allocation 없음
     *              SUM=0, formula=0 → 금액 일치 → canGenerate=true 검증
     */
    @IsTest
    static void testGetClaimDocInfo_SOC_LastPLAFalse_NoAlloc_CanGenerate() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        // Allocation 없음 → SUM = 0, formula = 0 → 일치 → canGenerate = true
        
        Test.startTest();
        CLM_QuickAction_Ctrl.ClaimDocInfoWrapper result = CLM_QuickAction_Ctrl.getClaimDocInfo(c.Id);
        Test.stopTest();
        
        Assert.areEqual(true, result.canGenerate, 'SOC + 금액 0 일치 → 생성 가능');
    }
    
    /**
     * @description [정상] ClaimDocType='SOC' + LastPLA_is__c=true + Allocation 존재
     *              컨트롤러는 금액 비교 없이 SOC+LastPLA=true → canGenerate=true 반환
     */
    @IsTest
    static void testGetClaimDocInfo_SOC_LastPLATrue_AmtMismatch_CannotGenerate() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = true;
        update c;
        
        CLM_Allocation__c alloc = new CLM_Allocation__c();
        alloc.Claim_md__c = c.Id;
        alloc.ClaimDocType__c = 'SOC';
        alloc.TotalAmtForRI__c = 200;
        insert alloc;
        
        Test.startTest();
        CLM_QuickAction_Ctrl.ClaimDocInfoWrapper result = CLM_QuickAction_Ctrl.getClaimDocInfo(c.Id);
        Test.stopTest();
        
        Assert.areEqual(true, result.canGenerate, 'SOC + LastPLA=true → 생성 가능');
    }
    
    /**
     * @description [정상] ClaimDocType='SOC' + LastPLA_is__c=false
     *              TotalAmtForRI__c=0, formula=0 → 금액 일치 → canGenerate=true 검증
     */
    @IsTest
    static void testGetClaimDocInfo_SOC_LastPLAFalse_AmtMatch_CanGenerate() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        // TotalAmtLK_fm__c = formula → 0, TotalAmtForRI__c = 0 → 일치 → canGenerate = true
        CLM_Allocation__c alloc = new CLM_Allocation__c();
        alloc.Claim_md__c = c.Id;
        alloc.ClaimDocType__c = 'SOC';
        alloc.TotalAmtForRI__c = 0;
        insert alloc;
        
        Test.startTest();
        CLM_QuickAction_Ctrl.ClaimDocInfoWrapper result = CLM_QuickAction_Ctrl.getClaimDocInfo(c.Id);
        Test.stopTest();
        
        Assert.areEqual(true, result.canGenerate, 'SOC + 금액 일치 → 생성 가능');
    }
    
    // ============================================================
    // Section 2. generateClaimDocument() 케이스 분기 테스트
    //   - Case 2: PLA + LastPLA=true
    //   - Case 3: SOC + LastPLA=false
    //   - Case 4: SOC + LastPLA=true
    //   - Allocation 포함 SOC 경로
    //   ※ DocGenerationBatchProcess DML은 관리 패키지 제한 → AuraHandledException으로 커버
    // ============================================================
    
    /**
     * @description [Case 2] ClaimDocType='PLA' + LastPLA_is__c=true
     *              → docTypeFilter={'PLA'}, PLA 템플릿 쿼리 실행
     *              → DocGenerationBatchProcess insert 시 관리 패키지 제한 → AuraHandledException catch 경로 커버
     */
    @IsTest
    static void testGenerateClaimDocument_Case2_PLA_LastPLATrue() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'PLA';
        c.LastPLA_is__c = true;
        update c;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (AuraHandledException e) {
            // 관리 패키지 DML 제한으로 인한 예외 - 정상 처리 경로
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [Case 3] ClaimDocType='SOC' + LastPLA_is__c=false
     *              → docTypeFilter={'SOC'}, SOC 템플릿 쿼리 실행
     *              → 관리 패키지 제한 → AuraHandledException catch 경로 커버
     */
    @IsTest
    static void testGenerateClaimDocument_Case3_SOC_NotLastPLA() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [Case 4] ClaimDocType='SOC' + LastPLA_is__c=true
     *              → docTypeFilter={'PLA','SOC'}, PLA+SOC 템플릿 쿼리 모두 실행
     *              → 관리 패키지 제한 → AuraHandledException catch 경로 커버
     */
    @IsTest
    static void testGenerateClaimDocument_Case4_SOC_LastPLATrue() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = true;
        update c;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [Allocation 포함] SOC + LastPLA=false + 일반 Allocation(FacilityBDXOffset=false) 존재
     *              → Allocation 조회 → docAllocs 분기 → groupMap 구성 경로 커버
     *              → 관리 패키지 제한 → AuraHandledException catch 경로 커버
     */
    @IsTest
    static void testGenerateClaimDocument_WithAllocations_SOC() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        CLM_Allocation__c alloc = new CLM_Allocation__c();
        alloc.Claim_md__c = c.Id;
        alloc.ClaimDocType__c = 'SOC';
        alloc.LossAmt__c = 100;
        alloc.ExpAmt__c = 10;
        alloc.TotalAmtForRI__c = 110;
        insert alloc;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    // ============================================================
    // Section 3. generateClaimDocument() - Facility Panel Allocation 경로 테스트
    //   - FacilityParticipant ClaimOffset=true  → offsetKeys 에 포함 → Allocation 제외
    //   - FacilityParticipant 없음              → offsetKeys 미포함  → Allocation 포함
    // ============================================================
    
    /**
     * @description [Facility 제외] Facility 타입 Panel Allocation + ClaimOffset_is__c=true FacilityParticipant
     *              → Panel의 Facility Id가 offsetKeys 에 포함 → 해당 Allocation continue(제외) 분기 커버
     */
    @IsTest
    static void testGenerateClaimDocument_WithFacilityAllocation_Excluded() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerExcluded', 'RE001');
        insert reinsurer;
        
        COM_Facility__c facility = new COM_Facility__c(Name = 'Test Facility Excluded');
        insert facility;
        
        Account oppAcc = makeAccount('TestOppAccExcluded', null);
        insert oppAcc;
        
        // RecordType 조회
        Id rtId = null;
        for (RecordTypeInfo rti : Schema.SObjectType.Opportunity.getRecordTypeInfos()) {
            if (rti.isAvailable() && !rti.isMaster() && rti.getName() == 'Reinsurance') {
                rtId = rti.getRecordTypeId();
                break;
            }
        }
        Opportunity opp = OPP_TestDataFactory.createOpportunity(oppAcc.Id, 'TestOppExcluded', rtId, true);
        OPP_Layer__c layer = OPP_TestDataFactory.createLayer(opp.Id, true);
        OPP_Panel__c panel = OPP_TestDataFactory.createPanel(layer.Id, false);
        panel.Facility_lk__c = facility.Id;
        panel.Reinsurer_lk__c = reinsurer.Id;
        insert panel;
        
        CLM_Allocation__c alloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'SOC', Panel_lk__c = panel.Id, TotalAmtForRI__c = 0);
        insert alloc;
        
        // ClaimOffset=true → offsetKeys 에 포함 → 해당 Allocation 제외
        COM_FacilityParticipant__c fp = new COM_FacilityParticipant__c(Facility_lk__c = facility.Id, ReinsurerAccount_lk__c = reinsurer.Id, ClaimOffset_is__c = true);
        insert fp;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [Facility 포함] Facility 타입 Panel Allocation + FacilityParticipant 없음
     *              → offsetKeys 에 해당 facilityId 미포함 → Allocation result.add(포함) 분기 커버
     */
    @IsTest
    static void testGenerateClaimDocument_WithFacilityAllocation_Included() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerIncluded', 'RE002');
        insert reinsurer;
        
        COM_Facility__c facility = new COM_Facility__c(Name = 'Test Facility Included');
        insert facility;
        
        Account oppAcc = makeAccount('TestOppAccIncluded', null);
        insert oppAcc;
        // RecordType 조회
        Id rtId = null;
        for (RecordTypeInfo rti : Schema.SObjectType.Opportunity.getRecordTypeInfos()) {
            if (rti.isAvailable() && !rti.isMaster() && rti.getName() == 'Reinsurance') {
                rtId = rti.getRecordTypeId();
                break;
            }
        }
        Opportunity opp = OPP_TestDataFactory.createOpportunity(oppAcc.Id, 'TestOppIncluded', rtId, true);
        OPP_Layer__c layer = OPP_TestDataFactory.createLayer(opp.Id, true);
        OPP_Panel__c panel = OPP_TestDataFactory.createPanel(layer.Id, false);
        panel.Facility_lk__c = facility.Id;
        panel.Reinsurer_lk__c = reinsurer.Id;
        insert panel;
        
        CLM_Allocation__c alloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'SOC', Panel_lk__c = panel.Id, TotalAmtForRI__c = 0);
        insert alloc;
        
        // FacilityParticipant 없음 → offsetKeys에 미포함 → Allocation 포함(result.add)
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [토큰 분기] Claim에 CedantName_lk__c + Placement_lk__c 설정,
     *              Allocation에 Reinsurer_lk__c 설정
     *              → baseTokenData ternary (CedantName_lk__r != null) true 분기 커버
     *              → groupMap reinsurerName (Reinsurer_lk__r != null) true 분기 커버
     */
    @IsTest
    static void testGenerateClaimDocument_WithCedantAndReinsurerLinks() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        Account cedant = makeAccount('TestCedantAccount', 'CE001');
        insert cedant;
        
        Placement__c placement = new Placement__c(RefType__c = '원수');
        insert placement;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerAccount', 'RE003');
        insert reinsurer;
        
        // CedantName_lk__c + Placement_lk__c 설정 → ternary true branch 커버
        c.CedantName_lk__c = cedant.Id;
        c.Placement_lk__c = placement.Id;
        update c;
        
        // Reinsurer_lk__c 설정 → groupMap reinsurerName true branch 커버
        CLM_Allocation__c alloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'SOC', Reinsurer_lk__c = reinsurer.Id, LossAmt__c = 50, ExpAmt__c = 5, TotalAmtForRI__c = 55);
        insert alloc;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [Case 4 + 복합 Allocation] SOC + LastPLA_is__c=true + PLA/SOC 두 타입 Allocation 모두 존재
     *              → docTypeFilter={PLA,SOC}, PLA+SOC 템플릿 쿼리 모두 실행
     *              → 두 타입 groupMap 구성 경로 커버
     */
    @IsTest
    static void testGenerateClaimDocument_Case4_WithBothDocTypeAllocations() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = true;
        update c;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerCase4', 'RE004');
        insert reinsurer;
        
        CLM_Allocation__c plaAlloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'PLA', Reinsurer_lk__c = reinsurer.Id, LossAmt__c = 100, TotalAmtForRI__c = 100);
        CLM_Allocation__c socAlloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'SOC', Reinsurer_lk__c = reinsurer.Id, LossAmt__c = 200, TotalAmtForRI__c = 200);
        insert new List<CLM_Allocation__c>{ plaAlloc, socAlloc };
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [금액 합산] 동일 (SOC + Panel) 그룹키 Allocation 2개
     *              → 첫 번째: groupMap.put(groupKey, grp)
     *              → 두 번째: groupMap.containsKey(groupKey)=true → lossAmt/expAmt/totalAmtForRI 누적 합산 분기 커버
     */
    @IsTest
    static void testGenerateClaimDocument_SameGroupKey_AmountAccumulation() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerSameGroup', 'RE005');
        insert reinsurer;
        
        // 동일 (SOC + reinsurer) 그룹키 → 두 번째 alloc은 금액만 합산
        CLM_Allocation__c alloc1 = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'SOC', Reinsurer_lk__c = reinsurer.Id, LossAmt__c = 100, ExpAmt__c = 10, TotalAmtForRI__c = 110);
        CLM_Allocation__c alloc2 = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'SOC', Reinsurer_lk__c = reinsurer.Id, LossAmt__c = 200, ExpAmt__c = 20, TotalAmtForRI__c = 220);
        insert new List<CLM_Allocation__c>{ alloc1, alloc2 };
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    // ============================================================
    // Section 4. generateClaimDocument() - DocumentTemplate 경로 테스트
    //   - PLA Template 존재 + ContentDoc 없음 → templateIdMap.put('PLA') + content empty 분기
    //   - SOC Template 존재 + ContentDoc 없음 → templateIdMap.put('SOC') + content empty 분기
    //   - PLA Template + ContentVersion + ContentDoc → templateContentVersionIdMap.put('PLA') 커버
    //   - Case 4 PLA+SOC 양쪽 Template+ContentDoc → 두 타입 dgpList.add 커버
    // ============================================================
    
    /**
     * @description [PLA Template, ContentDoc 없음] DocumentTemplate(TemplateType__c='PLA') insert 후 ContentDoc 미연결
     *              → templateIdMap.put('PLA', dt.Id) 커버
     *              → DocumentTemplateContentDoc 조회 isEmpty()=true → else(content empty) debug 분기 커버
     */
    @IsTest
    static void testGenerateClaimDocument_WithPLATemplate_NoContent() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'PLA';
        c.LastPLA_is__c = true;
        update c;
        
        CLM_Allocation__c alloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'PLA', LossAmt__c = 100, TotalAmtForRI__c = 100);
        insert alloc;
        
        DocumentTemplate dt = new DocumentTemplate(
            Name = 'TestPLATemplateNoContent',
        TemplateType__c = 'PLA',
        TokenMappingType = 'JSON',
        Type = 'MicrosoftWord',
        IsActive = true,
        TokenMappingMethodType = 'OmniDataTransform'
            );
        insert dt;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [SOC Template, ContentDoc 없음] DocumentTemplate(TemplateType__c='SOC') insert 후 ContentDoc 미연결
     *              → templateIdMap.put('SOC', dt.Id) 커버
     *              → DocumentTemplateContentDoc 조회 isEmpty()=true → else(content empty) debug 분기 커버
     */
    @IsTest
    static void testGenerateClaimDocument_WithSOCTemplate_NoContent() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        CLM_Allocation__c alloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'SOC', LossAmt__c = 200, TotalAmtForRI__c = 200);
        insert alloc;
        
        DocumentTemplate dt = new DocumentTemplate(
            Name = 'TestSOCTemplateNoContent',
        TemplateType__c = 'SOC',
        TokenMappingType = 'JSON',
        Type = 'MicrosoftWord',
        IsActive = true,
        TokenMappingMethodType = 'OmniDataTransform'
            );
        insert dt;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [PLA Template + ContentDoc 연결] ContentVersion → DocumentTemplateContentDoc 연결
     *              → LatestContentVersion.Id 조회 성공 → templateContentVersionIdMap.put('PLA') 커버
     *              → tokenData 구성 + dgpList.add 실행
     *              → DocumentGenerationProcess insert 또는 관리 패키지 제한 예외 catch 경로 커버
     */
    @IsTest
    static void testGenerateClaimDocument_WithPLATemplateAndContent() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'PLA';
        c.LastPLA_is__c = true;
        update c;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerPLAContent', 'RE006');
        insert reinsurer;
        
        CLM_Allocation__c alloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'PLA', Reinsurer_lk__c = reinsurer.Id, LossAmt__c = 100, ExpAmt__c = 10, TotalAmtForRI__c = 110);
        insert alloc;
        
        // ContentVersion 생성 → ContentDocument 자동 생성
        ContentVersion cv = new ContentVersion(Title = 'PLATemplateDoc', PathOnClient = 'PLATemplate.docx', VersionData = Blob.valueOf('PLA Template Content'), IsMajorVersion = true);
        insert cv;
        cv = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id LIMIT 1];
        
        DocumentTemplate dt = new DocumentTemplate(
            Name = 'TestPLATemplateWithContent',
        TemplateType__c = 'PLA',
        TokenMappingType = 'JSON',
        Type = 'MicrosoftWord',
        IsActive = true,
        TokenMappingMethodType = 'OmniDataTransform'
            );
        insert dt;
        
        // DocumentTemplateContentDoc 으로 Template ↔ ContentVersion 연결
        // → templateContentVersionIdMap.put('PLA', cv.Id) 경로 활성화
        DocumentTemplateContentDoc dtcd = new DocumentTemplateContentDoc(Name = 'TestDTCD', DocumentTemplateId = dt.Id, ContentDocumentId = cv.ContentDocumentId);
        insert dtcd;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [Case 4 + PLA/SOC 양쪽 Template+ContentDoc] SOC + LastPLA_is__c=true
     *              PLA ContentVersion+Template+ContentDoc, SOC ContentVersion+Template+ContentDoc 모두 연결
     *              → templateContentVersionIdMap.put('PLA') + put('SOC') 동시 커버
     *              → PLA/SOC 두 타입 dgpList.add 경로 커버
     */
    @IsTest
    static void testGenerateClaimDocument_Case4_WithBothTemplatesAndContent() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = true;
        update c;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerBothTemplates', 'RE007');
        insert reinsurer;
        
        CLM_Allocation__c plaAlloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'PLA', Reinsurer_lk__c = reinsurer.Id, LossAmt__c = 100, TotalAmtForRI__c = 100);
        CLM_Allocation__c socAlloc = new CLM_Allocation__c(Claim_md__c = c.Id, ClaimDocType__c = 'SOC', Reinsurer_lk__c = reinsurer.Id, LossAmt__c = 200, TotalAmtForRI__c = 200);
        insert new List<CLM_Allocation__c>{ plaAlloc, socAlloc };
        
        // PLA ContentVersion + Template + ContentDoc
        ContentVersion cvPla = new ContentVersion(Title = 'PLATemplateBothCase4', PathOnClient = 'PLACase4.docx', VersionData = Blob.valueOf('PLA Content'), IsMajorVersion = true);
        insert cvPla;
        cvPla = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cvPla.Id LIMIT 1];
        
        DocumentTemplate dtPla = new DocumentTemplate(
            Name = 'TestPLATemplateCase4',
        TemplateType__c = 'PLA',
        TokenMappingType = 'JSON',
        Type = 'MicrosoftWord',
        IsActive = true,
        TokenMappingMethodType = 'OmniDataTransform'
            );
        insert dtPla;
        
        DocumentTemplateContentDoc dtcdPla = new DocumentTemplateContentDoc(Name = 'TestDTCDPLA', DocumentTemplateId = dtPla.Id, ContentDocumentId = cvPla.ContentDocumentId);
        insert dtcdPla;
        
        // SOC ContentVersion + Template + ContentDoc
        ContentVersion cvSoc = new ContentVersion(Title = 'SOCTemplateBothCase4', PathOnClient = 'SOCCase4.docx', VersionData = Blob.valueOf('SOC Content'), IsMajorVersion = true);
        insert cvSoc;
        cvSoc = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cvSoc.Id LIMIT 1];
        
        DocumentTemplate dtSoc = new DocumentTemplate(
            Name = 'TestSOCTemplateCase4',
        TemplateType__c = 'SOC',
        TokenMappingType = 'JSON',
        Type = 'MicrosoftWord',
        IsActive = true,
        TokenMappingMethodType = 'OmniDataTransform'
            );
        insert dtSoc;
        
        DocumentTemplateContentDoc dtcdSoc = new DocumentTemplateContentDoc(Name = 'TestDTCDSOC', DocumentTemplateId = dtSoc.Id, ContentDocumentId = cvSoc.ContentDocumentId);
        insert dtcdSoc;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    // ============================================================
    // Section 5. assignAndUpdateClaimNoteSeqNo — offsetAllocs 경로 테스트
    //   - FacilityBDXOffset_is__c=true Allocation → offsetSeqMap 루프 커버
    //   - doc + offset 혼합 → 양쪽 경로 동시 커버
    //   - 동일 Panel offset 중복 → offsetSeqMap containsKey=true 분기 커버
    // ============================================================
    
    /**
     * @description [Offset Only] FacilityBDXOffset_is__c=true Allocation만 존재
     *              → docAllocs=empty, offsetAllocs=[alloc] → offsetSeqMap 루프 실행
     *              → ClaimNoteSeqNo__c 업데이트 경로 커버
     */
    @IsTest
    static void testGenerateClaimDocument_OffsetAllocOnly() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        CLM_Allocation__c offsetAlloc = new CLM_Allocation__c(
            Claim_md__c = c.Id,
        ClaimDocType__c = 'SOC',
        TotalAmtForRI__c = 50,
        FacilityBDXOffset_is__c = true
            );
        insert offsetAlloc;
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [Doc + Offset 혼합] FacilityBDXOffset=false 1건 + true 1건
     *              → docAllocs=[alloc1], offsetAllocs=[alloc2]
     *              → groupSeqMap 루프 + offsetSeqMap 루프 동시 커버
     */
    @IsTest
    static void testGenerateClaimDocument_DocAndOffsetAlloc_Mixed() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerMixed', 'RE010');
        insert reinsurer;
        
        CLM_Allocation__c docAlloc = new CLM_Allocation__c(
            Claim_md__c = c.Id,
        ClaimDocType__c = 'SOC',
        Reinsurer_lk__c = reinsurer.Id,
        LossAmt__c = 100,
        TotalAmtForRI__c = 100,
        FacilityBDXOffset_is__c = false
            );
        CLM_Allocation__c offsetAlloc = new CLM_Allocation__c(
            Claim_md__c = c.Id,
        ClaimDocType__c = 'SOC',
        Reinsurer_lk__c = reinsurer.Id,
        LossAmt__c = 50,
        TotalAmtForRI__c = 50,
        FacilityBDXOffset_is__c = true
            );
        insert new List<CLM_Allocation__c>{ docAlloc, offsetAlloc };
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    /**
     * @description [Offset 동일 Panel 중복] 같은 Panel의 Offset Allocation 2건
     *              → offsetSeqMap.containsKey(offsetKey)=true 분기(중복 skip) 커버
     */
    @IsTest
    static void testGenerateClaimDocument_OffsetAlloc_SamePanel_Dedup() {
        Claim c = getBaseClaim();
        c.ClaimDocType__c = 'SOC';
        c.LastPLA_is__c = false;
        update c;
        
        Account reinsurer = makeReinsurerAccount('TestReinsurerOffsetDedup', 'RE011');
        insert reinsurer;
        
        Account oppAcc = makeAccount('TestOppAccOffsetDedup', null);
        insert oppAcc;
        
        Id rtId = null;
        for (RecordTypeInfo rti : Schema.SObjectType.Opportunity.getRecordTypeInfos()) {
            if (rti.isAvailable() && !rti.isMaster() && rti.getName() == 'Reinsurance') {
                rtId = rti.getRecordTypeId();
                break;
            }
        }
        Opportunity opp = OPP_TestDataFactory.createOpportunity(oppAcc.Id, 'TestOppOffsetDedup', rtId, true);
        OPP_Layer__c layer = OPP_TestDataFactory.createLayer(opp.Id, true);
        OPP_Panel__c panel = OPP_TestDataFactory.createPanel(layer.Id, true);
        
        // 같은 Panel, Offset=true 2건 → 두 번째는 offsetSeqMap containsKey=true → skip
        CLM_Allocation__c offset1 = new CLM_Allocation__c(
            Claim_md__c = c.Id,
        ClaimDocType__c = 'SOC',
        Panel_lk__c = panel.Id,
        TotalAmtForRI__c = 30,
        FacilityBDXOffset_is__c = true
            );
        CLM_Allocation__c offset2 = new CLM_Allocation__c(
            Claim_md__c = c.Id,
        ClaimDocType__c = 'SOC',
        Panel_lk__c = panel.Id,
        TotalAmtForRI__c = 20,
        FacilityBDXOffset_is__c = true
            );
        insert new List<CLM_Allocation__c>{ offset1, offset2 };
        
        Test.startTest();
        try {
            CLM_QuickAction_Ctrl.generateClaimDocument(c.Id);
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException이어야 함');
            Assert.isNotNull(e.getMessage(), '예외 메시지가 있어야 함');
        }
        Test.stopTest();
    }
    
    // ============================================================
    // Section 7. ClaimDocInfoWrapper 테스트
    //   - 기본 생성자 기본값 검증
    //   - 필드 직접 할당 검증
    // ============================================================
    
    /**
     * @description [기본값] ClaimDocInfoWrapper 기본 생성자 호출
     *              canGenerate=false, lastPLA=false, hasEditPermission=false,
     *              claimDocType=null, message=null 검증
     */
    @IsTest
    static void testClaimDocInfoWrapper_DefaultValues() {
        Test.startTest();
        CLM_QuickAction_Ctrl.ClaimDocInfoWrapper w = new CLM_QuickAction_Ctrl.ClaimDocInfoWrapper();
        Test.stopTest();
        
        Assert.areEqual(false, w.canGenerate, '기본값 canGenerate=false');
        Assert.areEqual(false, w.lastPLA, '기본값 lastPLA=false');
        Assert.areEqual(false, w.hasEditPermission, '기본값 hasEditPermission=false');
        Assert.isNull(w.claimDocType, '기본값 claimDocType=null');
        Assert.isNull(w.message, '기본값 message=null');
    }
    
    /**
     * @description [필드 할당] ClaimDocInfoWrapper 각 @AuraEnabled 필드에 직접 값 설정 후
     *              할당된 값이 정확히 반환되는지 검증 (get/set 동작 확인)
     */
    @IsTest
    static void testClaimDocInfoWrapper_FieldAssignment() {
        Test.startTest();
        CLM_QuickAction_Ctrl.ClaimDocInfoWrapper w = new CLM_QuickAction_Ctrl.ClaimDocInfoWrapper();
        w.claimDocType = 'SOC';
        w.lastPLA = true;
        w.canGenerate = true;
        w.hasEditPermission = true;
        w.message = 'Test message';
        Test.stopTest();
        
        Assert.areEqual('SOC', w.claimDocType);
        Assert.areEqual(true, w.lastPLA);
        Assert.areEqual(true, w.canGenerate);
        Assert.areEqual(true, w.hasEditPermission);
        Assert.areEqual('Test message', w.message);
    }
}