force-app/main/default/objects/Account/fields/LKInternalRegion__c.field-meta.xml
<CustomField>
    <fullName>LKInternalRegion__c</fullName>
    <label>LK Internal Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_BizRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LK Ref. Name</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claim/recordTypes/Reinsurance.recordType-meta.xml
<RecordType>
    <fullName>Reinsurance</fullName>
    <active>true</active>
    <description>재보험 클레임</description>
    <label>Reinsurance</label>
</RecordType>

force-app/main/default/objects/OPP_Cobroker__c/OPP_Cobroker__c.object-meta.xml
<CustomObject>
    <label>Co-Broker</label>
    <nameField>
        <displayFormat>COB-{00000000}</displayFormat>
        <label>Co-Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Broker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Cobroker__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/Cobroker__c.field-meta.xml
<CustomField>
    <fullName>Cobroker__c</fullName>
    <label>(X)Co-broker</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_BizRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/CobrokerContact_lk__c.field-meta.xml
<CustomField>
    <fullName>CobrokerContact_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Co-Broker</relationshipLabel>
    <relationshipName>CoBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/CobrokerName_lk__c.field-meta.xml
<CustomField>
    <fullName>CobrokerName_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Co-Broker</relationshipLabel>
    <relationshipName>CoBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/CobrokerUser_lk__c.field-meta.xml
<CustomField>
    <fullName>CobrokerUser_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CoBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/CobrokingType__c.field-meta.xml
<CustomField>
    <fullName>CobrokingType__c</fullName>
    <label>Co-broking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producing</fullName>
            </value>
            <value>
                <fullName>Placing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/LKCobroker_lk__c.field-meta.xml
<CustomField>
    <fullName>LKCobroker_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Co-Broker (Co-broker)</relationshipLabel>
    <relationshipName>CoBrokerByLKCobroker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/LKCobroking_is__c.field-meta.xml
<CustomField>
    <fullName>LKCobroking_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LK Co-Broking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/Opportunity_md__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_md__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Co-Broker</relationshipLabel>
    <relationshipName>CoBrokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Co-Broker</relationshipLabel>
    <relationshipName>CoBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/SettlementType__c.field-meta.xml
<CustomField>
    <fullName>SettlementType__c</fullName>
    <label>Settlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Together</fullName>
            </value>
            <value>
                <fullName>Separate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/Sharing_is__c.field-meta.xml
<CustomField>
    <fullName>Sharing_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sharing Y/N</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/SharingPct__c.field-meta.xml
<CustomField>
    <fullName>SharingPct__c</fullName>
    <label>Sharing(%)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/OPP_Layer__c.object-meta.xml
<CustomObject>
    <label>Layer</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Layer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Layers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Layer__c/fields/Opportunity_md__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_md__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Layers</relationshipLabel>
    <relationshipName>Layers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Layers</relationshipLabel>
    <relationshipName>LayersAsPlacement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/OPP_Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Panel__c/fields/CoBroker_lk__c.field-meta.xml
<CustomField>
    <fullName>CoBroker_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Panels (Co-borker Name)</relationshipLabel>
    <relationshipName>PanelsAsCoBroker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/CoBrokerContact_lk__c.field-meta.xml
<CustomField>
    <fullName>CoBrokerContact_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placing Co-broker Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels (Placing Co-broker Contact)</relationshipLabel>
    <relationshipName>PanelsAsCoBroker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/CobrokingType__c.field-meta.xml
<CustomField>
    <fullName>CobrokingType__c</fullName>
    <label>Co-Broking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPO</fullName>
            </value>
            <value>
                <fullName>CPS</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CPT-CPO</fullName>
            </value>
            <value>
                <fullName>CPT-CPS</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Layer_md__c.field-meta.xml
<CustomField>
    <fullName>Layer_md__c</fullName>
    <label>Layer</label>
    <referenceTo>OPP_Layer__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Opportunity_lk__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/PlacingSettlementType__c.field-meta.xml
<CustomField>
    <fullName>PlacingSettlementType__c</fullName>
    <label>Settlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Separate</fullName>
            </value>
            <value>
                <fullName>Together</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/PlacingSharingPct__c.field-meta.xml
<CustomField>
    <fullName>PlacingSharingPct__c</fullName>
    <label>Sharing(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LKCobroker_lk__c.field-meta.xml
<CustomField>
    <fullName>LKCobroker_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-Owner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8)</booleanFilter>
        <filterItems>
            <field>$User.Region__c</field>
            <operation>equals</operation>
            <value>SG</value>
        </filterItems>
        <filterItems>
            <field>User.Region__c</field>
            <operation>equals</operation>
            <value>SG</value>
        </filterItems>
        <filterItems>
            <field>$User.Region__c</field>
            <operation>equals</operation>
            <value>KR</value>
        </filterItems>
        <filterItems>
            <field>User.Region__c</field>
            <operation>equals</operation>
            <value>KR</value>
        </filterItems>
        <filterItems>
            <field>$User.Region__c</field>
            <operation>equals</operation>
            <value>VN</value>
        </filterItems>
        <filterItems>
            <field>User.Region__c</field>
            <operation>equals</operation>
            <value>VN</value>
        </filterItems>
        <filterItems>
            <field>$User.Region__c</field>
            <operation>equals</operation>
            <value>A&amp;G</value>
        </filterItems>
        <filterItems>
            <field>User.Region__c</field>
            <operation>equals</operation>
            <value>A&amp;G</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NeedRecalculate_is__c.field-meta.xml
<CustomField>
    <fullName>NeedRecalculate_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Recalculate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Reinsurance.recordType-meta.xml
<RecordType>
    <fullName>Reinsurance</fullName>
    <active>true</active>
    <businessProcess>ReIns</businessProcess>
    <label>Reinsurance</label>
</RecordType>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>LK Ref. Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/CoBrokingType__c.field-meta.xml
<CustomField>
    <fullName>CoBrokingType__c</fullName>
    <label>Co-Broking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPO</fullName>
            </value>
            <value>
                <fullName>CPS</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>CPT-CPO</fullName>
            </value>
            <value>
                <fullName>CPT-CPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/NeedRecalculate_is__c.field-meta.xml
<CustomField>
    <fullName>NeedRecalculate_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Recalculate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Opportunity_lk__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/PlacementClosingDate__c.field-meta.xml
<CustomField>
    <fullName>PlacementClosingDate__c</fullName>
    <label>Send to Close date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/COM_BizRegion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LK_KR</fullName>
    </customValue>
    <customValue>
        <fullName>LK_Re</fullName>
    </customValue>
    <customValue>
        <fullName>LK_VN</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <masterLabel>[COM] Biz Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Opp_LkCoBroking_Ctrl_ts.cls
/**********************************************************************************
 * @filename      : Opp_LkCoBroking_Ctrl_ts.cls
 * @projectname   : LK_DEV2
 * @author        : i2max
 * @date          : 2026-01-14
 * @group         : Opportunity
 * @description   : Test class for Opp_LkCoBroking_Ctrl
 * @reference     : Opp_LkCoBroking_Ctrl.cls
 * @copyright     : LK Insurance Services
 * @modification  Log
 * ===================================================================
 * ver   date            author           description
 * ===================================================================
 * 1.0   2025-12-23      i2max            Create
 **********************************************************************************/
@IsTest
private class Opp_LkCoBroking_Ctrl_ts {
    /**
     * @description Setup test data
     */
    @TestSetup
    static void makeData() {
        // Create Account
        Account acc = (Account) ACC_TestDataFactory.createAccount('Test Account', 'General', true);
        
        // Create CoBroker Account
        Account coBrokerAcc = (Account) ACC_TestDataFactory.createAccount('Test CoBroker Account', 'Broker', true);
        
        // Create Contact
        Contact coBrokerContact = (Contact) COM_TestDataFactory.createSObject(
            'Contact',
        new Map<String, Object>{ 'LastName' => 'Test Contact', 'AccountId' => coBrokerAcc.Id, 'OwnerId' => UserInfo.getUserId() },
        true
            );
        
        // RecordType 조회 (Reinsurance RecordType 사용)
        Id rtId = null;
        for (RecordTypeInfo rti : Schema.SObjectType.Opportunity.getRecordTypeInfos()) {
            if (rti.isAvailable() && !rti.isMaster() && rti.getName() == 'Reinsurance') {
                rtId = rti.getRecordTypeId();
                System.debug('Selected RecordType: ' + rti.getName());
                break;
            }
        }
        
        // Reinsurance RecordType이 없으면 첫 번째 사용 가능한 RecordType 사용
        if (rtId == null) {
            for (RecordTypeInfo rti : Schema.SObjectType.Opportunity.getRecordTypeInfos()) {
                if (rti.isAvailable() && !rti.isMaster()) {
                    rtId = rti.getRecordTypeId();
                    System.debug('Fallback RecordType: ' + rti.getName());
                    break;
                }
            }
        }
        
        // Create Opportunities using TestDataFactory
        Opportunity opp1 = OPP_TestDataFactory.createOpportunity(acc.Id, 'Test Opp 1', rtId, true);
        Opportunity opp2 = OPP_TestDataFactory.createOpportunity(acc.Id, 'Test Opp 2', rtId, true);
        
        // Create LK Co-Brokers for Opp1
        List<OPP_Cobroker__c> coBrokers = new List<OPP_Cobroker__c>();
        
        // LK Co-Broker 1: Placing
        OPP_Cobroker__c cb1 = (OPP_Cobroker__c) COM_TestDataFactory.createSObject(
            'OPP_Cobroker__c',
        new Map<String, Object>{
            'Opportunity_md__c' => opp1.Id,
            'LKCobroking_is__c' => true,
            'CobrokingType__c' => 'Placing',
            'SettlementType__c' => 'Together',
            'SharingPct__c' => 30,
            'Client__c' => false,
            'Sharing_is__c' => false
        },
        false
            );
        coBrokers.add(cb1);
        
        // LK Co-Broker 2: Producing
        OPP_Cobroker__c cb2 = (OPP_Cobroker__c) COM_TestDataFactory.createSObject(
            'OPP_Cobroker__c',
        new Map<String, Object>{
            'Opportunity_md__c' => opp1.Id,
            'LKCobroking_is__c' => true,
            'CobrokingType__c' => 'Producing',
            'SettlementType__c' => 'Separate',
            'SharingPct__c' => 20,
            'Client__c' => false,
            'Sharing_is__c' => false
        },
        false
            );
        coBrokers.add(cb2);
        
        // Non-LK Co-Broker for Opp1 (should be filtered out in getCoBrokerList)
        OPP_Cobroker__c cb3 = (OPP_Cobroker__c) COM_TestDataFactory.createSObject(
            'OPP_Cobroker__c',
        new Map<String, Object>{
            'Opportunity_md__c' => opp1.Id,
            'LKCobroking_is__c' => false,
            'CobrokingType__c' => 'Placing',
            'SettlementType__c' => 'Together',
            'SharingPct__c' => 10,
            'Client__c' => false,
            'Sharing_is__c' => false
        },
        false
            );
        coBrokers.add(cb3);
        
        // LK Co-Broker for Opp2
        OPP_Cobroker__c cb4 = (OPP_Cobroker__c) COM_TestDataFactory.createSObject(
            'OPP_Cobroker__c',
        new Map<String, Object>{
            'Opportunity_md__c' => opp2.Id,
            'LKCobroking_is__c' => true,
            'CobrokingType__c' => 'Placing',
            'SettlementType__c' => 'Together',
            'SharingPct__c' => 25,
            'Client__c' => false,
            'Sharing_is__c' => false
        },
        false
            );
        coBrokers.add(cb4);
        
        // Non-LK producing co-broker for conflict checks
        OPP_Cobroker__c producingConflict = (OPP_Cobroker__c) COM_TestDataFactory.createSObject(
            'OPP_Cobroker__c',
        new Map<String, Object>{
            'Opportunity_md__c' => opp1.Id,
            'LKCobroking_is__c' => false,
            'CobrokingType__c' => 'Producing',
            'SettlementType__c' => 'Separate',
            'SharingPct__c' => 15,
            'Client__c' => true,
            'CobrokerName_lk__c' => coBrokerAcc.Id,
            'CobrokerContact_lk__c' => coBrokerContact.Id,
            'Sharing_is__c' => false
        },
        false
            );
        coBrokers.add(producingConflict);
        
        insert coBrokers;
        
        // Create Layer using TestDataFactory
        OPP_Layer__c layer = OPP_TestDataFactory.createLayer(opp1.Id, true);
        
        // Create Panel using TestDataFactory
        OPP_Panel__c panel = OPP_TestDataFactory.createPanel(layer.Id, false);
        panel.CoBroker_lk__c = coBrokerAcc.Id;
        panel.PlacingSharingPct__c = 10;
        panel.PlacingSettlementType__c = 'Separate';
        insert panel;
    }
    /**
     * @description Test getInitData - CoBrokerList Success
     */
    @IsTest
    static void testGetInitData_CoBrokerList_Success() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(opp.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, w.coBrokerList, 'Co-Broker list should not be null');
        System.assertEquals(2, w.coBrokerList.size(), 'Should return only LK Co-Brokers (LKCobroking_is__c = true)');
        
        // Verify ordering by CobrokingType__c
        System.assertEquals('Producing', w.coBrokerList[0].CobrokingType__c, 'First should be Producing');
        System.assertEquals('Placing', w.coBrokerList[1].CobrokingType__c, 'Second should be Placing');
        
        // Verify isPlacement field
        System.assertEquals(false, w.isPlacement, 'isPlacement should be false for Opportunity');
    }
    
    /**
     * @description Test getInitData - Filters by Opportunity
     */
    @IsTest
    static void testGetInitData_FiltersByOpportunity() {
        List<Opportunity> opps = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC];
        Opportunity opp1 = opps[0];
        Opportunity opp2 = opps.size() > 1 ? opps[1] : opps[0];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.InitDataWrapper w1 = Opp_LkCoBroking_Ctrl.getInitData(opp1.Id);
        Opp_LkCoBroking_Ctrl.InitDataWrapper w2 = Opp_LkCoBroking_Ctrl.getInitData(opp2.Id);
        Test.stopTest();
        
        System.assertEquals(2, w1.coBrokerList.size(), 'Opp1 should have 2 LK Co-Brokers');
        System.assertEquals(1, w2.coBrokerList.size(), 'Opp2 should have 1 LK Co-Broker');
    }
    
    /**
     * @description Test saveCoBrokers - Insert New Records
     */
    @IsTest
    static void testSaveCoBrokers_InsertNew() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        OPP_Cobroker__c newCoBroker = new OPP_Cobroker__c();
        newCoBroker.CobrokingType__c = 'Placing';
        newCoBroker.SettlementType__c = 'Together';
        newCoBroker.SharingPct__c = 15;
        newCoBroker.Client__c = true;
        newCoBroker.Sharing_is__c = true;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ newCoBroker }, opp.Id, null, false);
        Test.stopTest();
        
        Integer count = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroking_is__c = TRUE
        ];
        System.assertEquals(3, count, 'Should have 3 Co-Brokers (2 existing + 1 new)');
        
        // Verify new record was saved with correct values
        List<OPP_Cobroker__c> savedRecords = [
            SELECT Id, Opportunity_md__c, LKCobroking_is__c, CobrokingType__c, SettlementType__c, SharingPct__c, Client__c, Sharing_is__c
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Placing' AND SharingPct__c = 15
        ];
        System.assertEquals(1, savedRecords.size(), 'New record should be saved');
        System.assertEquals(opp.Id, savedRecords[0].Opportunity_md__c, 'Opportunity should be linked');
        System.assertEquals(true, savedRecords[0].LKCobroking_is__c, 'LKCobroking_is__c should be true');
        System.assertEquals(15, savedRecords[0].SharingPct__c, 'SharingPct should be 15');
        System.assertEquals(true, savedRecords[0].Client__c, 'Client should be true');
        System.assertEquals(true, savedRecords[0].Sharing_is__c, 'Sharing_is__c should be true');
    }
    
    /**
     * @description Test saveCoBrokers - Update Existing Record
     */
    @IsTest
    static void testSaveCoBrokers_UpdateExisting() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        OPP_Cobroker__c existing = [
            SELECT Id, CobrokingType__c, Cobroker__c, CobrokerUser_lk__c, SettlementType__c, SharingPct__c, Sharing_is__c, Client__c, LKCobroker_lk__c
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroking_is__c = TRUE
            LIMIT 1
        ];
        
        // Update values
        existing.SharingPct__c = 50;
        existing.SettlementType__c = 'Separate';
        existing.Client__c = true;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ existing }, opp.Id, null, false);
        Test.stopTest();
        
        // Verify update
        OPP_Cobroker__c updated = [
            SELECT Id, SharingPct__c, SettlementType__c, Client__c, Opportunity_md__c, LKCobroking_is__c
            FROM OPP_Cobroker__c
            WHERE Id = :existing.Id
        ];
        System.assertEquals(50, updated.SharingPct__c, 'SharingPct should be updated to 50');
        System.assertEquals('Separate', updated.SettlementType__c, 'SettlementType should be updated to Separate');
        System.assertEquals(true, updated.Client__c, 'Client should be updated to true');
        System.assertEquals(opp.Id, updated.Opportunity_md__c, 'Opportunity linkage should remain');
        System.assertEquals(true, updated.LKCobroking_is__c, 'LKCobroking_is__c should remain true');
    }
    
    /**
     * @description Test saveCoBrokers - Null Value Defaults
     */
    @IsTest
    static void testSaveCoBrokers_NullDefaults() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        OPP_Cobroker__c newCoBroker = new OPP_Cobroker__c();
        newCoBroker.CobrokingType__c = 'Placing';
        newCoBroker.SettlementType__c = 'Together';
        newCoBroker.SharingPct__c = null; // Should default to 0
        newCoBroker.Client__c = null; // Should default to false
        newCoBroker.Sharing_is__c = null; // Should default to false
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ newCoBroker }, opp.Id, null, false);
        Test.stopTest();
        
        // Verify defaults were applied
        List<OPP_Cobroker__c> savedRecords = [
            SELECT Id, SharingPct__c, Client__c, Sharing_is__c
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Placing' AND SharingPct__c = 0
        ];
        System.assertEquals(1, savedRecords.size(), 'Record should be saved with defaults');
        System.assertEquals(0, savedRecords[0].SharingPct__c, 'Null SharingPct should default to 0');
        System.assertEquals(false, savedRecords[0].Client__c, 'Null Client should default to false');
        System.assertEquals(false, savedRecords[0].Sharing_is__c, 'Null Sharing_is__c should default to false');
    }
    
    /**
     * @description Test saveCoBrokers - Empty List Exception
     */
    @IsTest
    static void testSaveCoBrokers_EmptyList() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        try {
            Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>(), opp.Id, null, false);
            System.assert(false, 'Expected AuraHandledException');
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException 이어야 합니다.');
        }
        Test.stopTest();
    }
    
    /**
     * @description Test saveCoBrokers - Null List Exception
     */
    @IsTest
    static void testSaveCoBrokers_NullList() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        try {
            Opp_LkCoBroking_Ctrl.saveCoBrokers(null, opp.Id, null, false);
            System.assert(false, 'Expected AuraHandledException');
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException 이어야 합니다.');
        }
        Test.stopTest();
    }
    
    /**
     * @description Test deleteCoBrokers - Success
     */
    @IsTest
    static void testDeleteCoBrokers_Success() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        List<OPP_Cobroker__c> coBrokers = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroking_is__c = TRUE
        ];
        System.assertEquals(2, coBrokers.size(), 'Should have 2 LK Co-Brokers before deletion');
        
        Id deleteId = coBrokers[0].Id;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.deleteCoBrokers(new List<Id>{ deleteId }, opp.Id, null);
        Test.stopTest();
        
        // Verify deletion
        List<OPP_Cobroker__c> afterDelete = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Id = :deleteId
        ];
        System.assertEquals(0, afterDelete.size(), 'Co-Broker should be deleted');
        
        // Verify other records remain
        List<OPP_Cobroker__c> remaining = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroking_is__c = TRUE
        ];
        System.assertEquals(1, remaining.size(), 'Other Co-Broker should remain');
    }
    
    /**
     * @description Test deleteCoBrokers - Empty List (No-op)
     */
    @IsTest
    static void testDeleteCoBrokers_EmptyList() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Integer beforeCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id
        ];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.deleteCoBrokers(new List<Id>(), opp.Id, null);
        Test.stopTest();
        
        Integer afterCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id
        ];
        System.assertEquals(beforeCount, afterCount, 'No records should be deleted for empty list');
    }
    
    /**
     * @description Test deleteCoBrokers - Null List (No-op)
     */
    @IsTest
    static void testDeleteCoBrokers_NullList() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Integer beforeCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id
        ];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.deleteCoBrokers(null, opp.Id, null);
        Test.stopTest();
        
        Integer afterCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id
        ];
        System.assertEquals(beforeCount, afterCount, 'No records should be deleted for null list');
    }
    
    /**
     * @description Test deleteCoBrokers - Filters by Opportunity and LK Flag
     */
    @IsTest
    static void testDeleteCoBrokers_FiltersByOpportunity() {
        List<Opportunity> opps = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC];
        Opportunity opp1 = opps[0];
        Opportunity opp2 = opps.size() > 1 ? opps[1] : opps[0];
        
        OPP_Cobroker__c opp2CoBroker = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp2.Id AND LKCobroking_is__c = TRUE
            LIMIT 1
        ];
        
        Test.startTest();
        // Try to delete Opp2's Co-Broker using Opp1's ID - should not delete
        Opp_LkCoBroking_Ctrl.deleteCoBrokers(new List<Id>{ opp2CoBroker.Id }, opp1.Id, null);
        Test.stopTest();
        
        // Verify record was NOT deleted (protected by WHERE clause filter)
        List<OPP_Cobroker__c> afterDelete = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Id = :opp2CoBroker.Id
        ];
        System.assertEquals(1, afterDelete.size(), 'Co-Broker from different Opp should not be deleted');
    }
    
    /**
     * @description Test getInitData - producingDisabled condition met
     */
    @IsTest
    static void testGetInitData_ProducingDisabled_True() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(opp.Id);
        Test.stopTest();
        
        System.assertEquals(true, w.producingDisabled, 'Producing should be disabled because a conflicting record exists.');
    }
    
    /**
     * @description Test getInitData - producingDisabled condition not met
     */
    @IsTest
    static void testGetInitData_ProducingDisabled_False() {
        List<Opportunity> opps = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC];
        Opportunity opp = opps.size() > 1 ? opps[1] : opps[0];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(opp.Id);
        Test.stopTest();
        
        System.assertEquals(false, w.producingDisabled, 'Producing should not be disabled for Opp2.');
    }
    
    /**
     * @description Test checkPreSaveConflicts - has both conflicts
     */
    @IsTest
    static void testCheckPreSaveConflicts_HasBoth() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result = Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(opp.Id, null, true, true);
        Test.stopTest();
        
        System.assertEquals(true, result.hasAny, 'Should have conflicts.');
        System.assertEquals(true, result.hasProducingConflicts, 'Should have producing conflicts.');
        System.assertEquals(true, result.hasPlacingConflicts, 'Should have placing conflicts.');
        System.assertEquals(1, result.producingConflicts.size(), 'Should find 1 producing conflict.');
        System.assertEquals(1, result.placingPanelConflicts.size(), 'Should find 1 placing conflict.');
    }
    
    /**
     * @description Test checkPreSaveConflicts - no conflicts
     */
    @IsTest
    static void testCheckPreSaveConflicts_NoConflicts() {
        List<Opportunity> opps = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC];
        Opportunity opp = opps.size() > 1 ? opps[1] : opps[0];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result = Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(opp.Id, null, true, true);
        Test.stopTest();
        
        System.assertEquals(false, result.hasAny, 'Should have no conflicts.');
        System.assertEquals(false, result.hasProducingConflicts, 'Should have no producing conflicts.');
        System.assertEquals(false, result.hasPlacingConflicts, 'Should have no placing conflicts.');
    }
    
    /**
     * @description Test resolvePreSaveConflicts - resolve both conflicts
     */
    @IsTest
    static void testResolvePreSaveConflicts_ResolveBoth() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(opp.Id, null, true, true);
        Test.stopTest();
        
        Integer producingConflicts = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        System.assertEquals(0, producingConflicts, 'Producing conflict should be deleted.');
        
        Integer placingConflicts = [
            SELECT COUNT()
            FROM OPP_Panel__c
            WHERE Layer_md__r.Opportunity_md__c = :opp.Id AND CoBroker_lk__c != NULL
        ];
        System.assertEquals(0, placingConflicts, 'Placing conflict should be cleared.');
    }
    
    /**
     * @description Test resolvePreSaveConflicts - resolve only placing
     */
    @IsTest
    static void testResolvePreSaveConflicts_ResolvePlacingOnly() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(opp.Id, null, false, true);
        Test.stopTest();
        
        Integer producingConflicts = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        System.assertEquals(1, producingConflicts, 'Producing conflict should NOT be deleted.');
        
        Integer placingConflicts = [
            SELECT COUNT()
            FROM OPP_Panel__c
            WHERE Layer_md__r.Opportunity_md__c = :opp.Id AND CoBroker_lk__c != NULL
        ];
        System.assertEquals(0, placingConflicts, 'Placing conflict should be cleared.');
    }
    
    /**
     * @description saveCoBrokers - catch (DmlException) 커버
     *              삭제된 레코드 Id로 upsert 시 ENTITY_IS_DELETED DmlException 유도
     */
    @IsTest
    static void testSaveCoBrokers_DmlExceptionCatch() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        // 레코드 생성 후 삭제 → 삭제된 Id를 controller에 전달 → upsert → ENTITY_IS_DELETED DmlException
        OPP_Cobroker__c tempRecord = new OPP_Cobroker__c(Opportunity_md__c = opp.Id, CobrokingType__c = 'Placing', SettlementType__c = 'Together', LKCobroking_is__c = true);
        insert tempRecord;
        Id deletedId = tempRecord.Id;
        delete tempRecord;
        
        OPP_Cobroker__c recordWithDeletedId = new OPP_Cobroker__c(Id = deletedId, CobrokingType__c = 'Placing', SettlementType__c = 'Together');
        
        Test.startTest();
        try {
            Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ recordWithDeletedId }, opp.Id, null, false);
            System.assert(false, 'DmlException이 발생해야 함');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().contains('Script-thrown exception'), 'DmlException catch 경로 실행 확인: ' + e.getMessage());
        }
        Test.stopTest();
    }
    
    /**
     * @description Test deleteCoBrokers - DML Exception handling
     */
    @IsTest
    static void testDeleteCoBrokers_WithTriggerError() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        List<OPP_Cobroker__c> coBrokers = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroking_is__c = TRUE
            LIMIT 1
        ];
        
        // Note: Actual DML exception is hard to trigger in delete operation
        // This test verifies the exception handling structure exists
        Test.startTest();
        try {
            // Normal delete should succeed
            Opp_LkCoBroking_Ctrl.deleteCoBrokers(new List<Id>{ coBrokers[0].Id }, opp.Id, null);
            System.assert(true, 'Delete should succeed normally');
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException 이어야 합니다.');
        }
        Test.stopTest();
    }
    
    /**
     * @description Test checkPreSaveConflicts - Blank Opportunity ID
     */
    @IsTest
    static void testCheckPreSaveConflicts_BlankOppId() {
        Test.startTest();
        Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result = Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(null, null, true, true);
        Test.stopTest();
        
        System.assertEquals(false, result.hasAny, 'Should have no conflicts for blank ID');
        System.assertEquals(false, result.hasProducingConflicts, 'Should have no producing conflicts');
        System.assertEquals(false, result.hasPlacingConflicts, 'Should have no placing conflicts');
        System.assertEquals(0, result.producingConflicts.size(), 'Should have empty list');
        System.assertEquals(0, result.placingPanelConflicts.size(), 'Should have empty list');
    }
    
    /**
     * @description Test resolvePreSaveConflicts - Blank Opportunity ID (no-op)
     */
    @IsTest
    static void testResolvePreSaveConflicts_BlankOppId() {
        Test.startTest();
        // Should not throw exception, just return without doing anything
        Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(null, null, true, true);
        Test.stopTest();
        
        // If we get here without exception, the test passed
        System.assert(true, 'Should handle blank ID gracefully');
    }
    
    /**
     * @description Test resolvePreSaveConflicts - Resolve only producing
     */
    @IsTest
    static void testResolvePreSaveConflicts_ResolveProducingOnly() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(opp.Id, null, true, false);
        Test.stopTest();
        
        Integer producingConflicts = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        System.assertEquals(0, producingConflicts, 'Producing conflict should be deleted.');
        
        Integer placingConflicts = [
            SELECT COUNT()
            FROM OPP_Panel__c
            WHERE Layer_md__r.Opportunity_md__c = :opp.Id AND CoBroker_lk__c != NULL
        ];
        System.assertEquals(1, placingConflicts, 'Placing conflict should NOT be cleared.');
    }
    
    /**
     * @description Test checkPreSaveConflicts - Only check Producing
     */
    @IsTest
    static void testCheckPreSaveConflicts_OnlyProducing() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result = Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(opp.Id, null, true, false);
        Test.stopTest();
        
        System.assertEquals(true, result.hasProducingConflicts, 'Should have producing conflicts.');
        System.assertEquals(false, result.hasPlacingConflicts, 'Should not check placing conflicts.');
        System.assertEquals(1, result.producingConflicts.size(), 'Should find 1 producing conflict.');
        System.assertEquals(0, result.placingPanelConflicts.size(), 'Should have empty placing list.');
    }
    
    /**
     * @description Test checkPreSaveConflicts - Only check Placing
     */
    @IsTest
    static void testCheckPreSaveConflicts_OnlyPlacing() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result = Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(opp.Id, null, false, true);
        Test.stopTest();
        
        System.assertEquals(false, result.hasProducingConflicts, 'Should not check producing conflicts.');
        System.assertEquals(true, result.hasPlacingConflicts, 'Should have placing conflicts.');
        System.assertEquals(0, result.producingConflicts.size(), 'Should have empty producing list.');
        System.assertEquals(1, result.placingPanelConflicts.size(), 'Should find 1 placing conflict.');
    }
    
    /**
     * @description Test resolvePreSaveConflicts - Exception handling with rollback
     * Note: This test verifies that the exception handling and rollback logic is in place.
     * Actual DML exceptions are difficult to trigger without validation rules or triggers.
     */
    @IsTest
    static void testResolvePreSaveConflicts_ExceptionHandling() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        // Count initial records
        Integer initialProducingCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        Integer initialPlacingCount = [
            SELECT COUNT()
            FROM OPP_Panel__c
            WHERE Layer_md__r.Opportunity_md__c = :opp.Id AND CoBroker_lk__c != NULL
        ];
        
        Test.startTest();
        try {
            // Attempt to resolve conflicts
            // If there are triggers or validation rules that throw exceptions, they will be caught
            Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(opp.Id, null, true, true);
            
            // If no exception occurs, verify the resolution was successful
            Integer finalProducingCount = [
                SELECT COUNT()
                FROM OPP_Cobroker__c
                WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
            ];
            Integer finalPlacingCount = [
                SELECT COUNT()
                FROM OPP_Panel__c
                WHERE Layer_md__r.Opportunity_md__c = :opp.Id AND CoBroker_lk__c != NULL
            ];
            
            System.assertEquals(0, finalProducingCount, 'Producing conflicts should be resolved');
            System.assertEquals(0, finalPlacingCount, 'Placing conflicts should be resolved');
        } catch (AuraHandledException e) {
            // If exception occurs, verify error message format
            System.assert(e.getMessage().contains('Error resolving conflicts'), 'Should throw appropriate error message');
            
            // Verify rollback occurred - data should remain unchanged
            Integer rollbackProducingCount = [
                SELECT COUNT()
                FROM OPP_Cobroker__c
                WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
            ];
            Integer rollbackPlacingCount = [
                SELECT COUNT()
                FROM OPP_Panel__c
                WHERE Layer_md__r.Opportunity_md__c = :opp.Id AND CoBroker_lk__c != NULL
            ];
            
            System.assertEquals(initialProducingCount, rollbackProducingCount, 'Rollback should restore producing conflicts');
            System.assertEquals(initialPlacingCount, rollbackPlacingCount, 'Rollback should restore placing conflicts');
        }
        Test.stopTest();
    }
    
    /**
     * @description Test resolvePreSaveConflicts - False parameters (no-op)
     */
    @IsTest
    static void testResolvePreSaveConflicts_NoResolution() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Integer initialProducingCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        Integer initialPlacingCount = [
            SELECT COUNT()
            FROM OPP_Panel__c
            WHERE Layer_md__r.Opportunity_md__c = :opp.Id AND CoBroker_lk__c != NULL
        ];
        
        Test.startTest();
        // Call with both parameters false - should not resolve anything
        Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(opp.Id, null, false, false);
        Test.stopTest();
        
        Integer finalProducingCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        Integer finalPlacingCount = [
            SELECT COUNT()
            FROM OPP_Panel__c
            WHERE Layer_md__r.Opportunity_md__c = :opp.Id AND CoBroker_lk__c != NULL
        ];
        
        System.assertEquals(initialProducingCount, finalProducingCount, 'Should not delete producing conflicts');
        System.assertEquals(initialPlacingCount, finalPlacingCount, 'Should not clear placing conflicts');
    }
    
    /**
     * @description Test getInitData - Exception handling (null / non-existent ID)
     */
    @IsTest
    static void testGetInitData_ExceptionHandling() {
        Test.startTest();
        
        // Test with null ID
        try {
            Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(null);
            System.assertNotEquals(null, w.coBrokerList, 'Should return empty list for null ID');
            System.assertEquals(0, w.coBrokerList.size(), 'Should have no records for null ID');
            System.assertEquals(false, w.producingDisabled, 'Should return false for null ID');
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException 이어야 합니다.');
        }
        
        // Test with non-existent ID - should return false (count = 0)
        Id nonExistentId = '006000000000000AAA';
        try {
            Opp_LkCoBroking_Ctrl.InitDataWrapper w2 = Opp_LkCoBroking_Ctrl.getInitData(nonExistentId);
            System.assertEquals(false, w2.producingDisabled, 'Should return false for non-existent ID');
        } catch (Exception e) {
            System.assert(e instanceof AuraHandledException, 'AuraHandledException 이어야 합니다.');
        }
        
        Test.stopTest();
    }
    
    /**
     * @description Test saveCoBrokers - All null fields with defaults
     */
    @IsTest
    static void testSaveCoBrokers_AllNullFields() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        OPP_Cobroker__c newRecord = new OPP_Cobroker__c();
        newRecord.CobrokingType__c = 'Placing';
        newRecord.SettlementType__c = 'Together';
        newRecord.Cobroker__c = null;
        newRecord.CobrokerUser_lk__c = null;
        newRecord.Client__c = null;
        newRecord.Sharing_is__c = null;
        newRecord.SharingPct__c = null;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ newRecord }, opp.Id, null, false);
        Test.stopTest();
        
        OPP_Cobroker__c saved = [
            SELECT Id, Client__c, Sharing_is__c, SharingPct__c, LKCobroking_is__c
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Placing' AND SharingPct__c = 0
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        
        System.assertEquals(false, saved.Client__c, 'Client should default to false');
        System.assertEquals(false, saved.Sharing_is__c, 'Sharing_is__c should default to false');
        System.assertEquals(0, saved.SharingPct__c, 'SharingPct should default to 0');
        System.assertEquals(true, saved.LKCobroking_is__c, 'LKCobroking_is__c should be set to true');
    }
    
    /**
     * @description Test saveCoBrokers - Mixed insert and update
     */
    @IsTest
    static void testSaveCoBrokers_MixedOperations() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        OPP_Cobroker__c existing = [
            SELECT Id, CobrokingType__c, Cobroker__c, LKCobroker_lk__c, CobrokerUser_lk__c, SettlementType__c, SharingPct__c, Sharing_is__c, Client__c
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroking_is__c = TRUE
            LIMIT 1
        ];
        
        existing.SharingPct__c = 40;
        
        OPP_Cobroker__c newRecord = new OPP_Cobroker__c();
        newRecord.CobrokingType__c = 'Producing';
        newRecord.SettlementType__c = 'Separate';
        newRecord.SharingPct__c = 25;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ existing, newRecord }, opp.Id, null, false);
        Test.stopTest();
        
        OPP_Cobroker__c updated = [
            SELECT Id, SharingPct__c
            FROM OPP_Cobroker__c
            WHERE Id = :existing.Id
        ];
        System.assertEquals(40, updated.SharingPct__c, 'Existing record should be updated');
    }
    
    /**
     * @description Test saveCoBrokers - LKCobroker_lk__c / CobrokerUser_lk__c / Client__c(true) 필드
     *              실제 lookup 값을 설정하여 해당 필드 할당 분기를 커버한다.
     */
    @IsTest
    static void testSaveCoBrokers_WithLookupFields() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        // @TestSetup Account 이름 의존 대신 테스트 내 직접 생성
        Account coBrokerAcc = ACC_TestDataFactory.createAccount('LookupField Test CoBroker', 'Broker', true);
        
        Id currentUserId = UserInfo.getUserId();
        
        OPP_Cobroker__c newRecord = new OPP_Cobroker__c();
        newRecord.CobrokingType__c = 'Placing';
        newRecord.SettlementType__c = 'Together';
        newRecord.SharingPct__c = 10;
        newRecord.LKCobroker_lk__c = coBrokerAcc.Id; // lookup 비-null 할당 커버
        newRecord.CobrokerUser_lk__c = currentUserId; // lookup 비-null 할당 커버
        newRecord.Client__c = true; // null 아닌 true 분기 커버
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ newRecord }, opp.Id, null, false);
        Test.stopTest();
        
        List<OPP_Cobroker__c> saved = [
            SELECT Id, LKCobroker_lk__c, CobrokerUser_lk__c, Client__c
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroker_lk__c = :coBrokerAcc.Id
            LIMIT 1
        ];
        Assert.areEqual(1, saved.size(), '저장된 레코드가 1개여야 함');
        Assert.areEqual(coBrokerAcc.Id, saved[0].LKCobroker_lk__c, 'LKCobroker_lk__c가 일치해야 함');
        Assert.areEqual(currentUserId, saved[0].CobrokerUser_lk__c, 'CobrokerUser_lk__c가 일치해야 함');
        Assert.isTrue(saved[0].Client__c, 'Client__c가 true여야 함');
    }
    
    /**
     * @description Test deleteCoBrokers - Non-LK Co-Broker protection
     */
    @IsTest
    static void testDeleteCoBrokers_NonLKProtection() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        OPP_Cobroker__c nonLKCoBroker = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroking_is__c = FALSE
            LIMIT 1
        ];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.deleteCoBrokers(new List<Id>{ nonLKCoBroker.Id }, opp.Id, null);
        Test.stopTest();
        
        List<OPP_Cobroker__c> afterDelete = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Id = :nonLKCoBroker.Id
        ];
        System.assertEquals(1, afterDelete.size(), 'Non-LK Co-Broker should not be deleted');
    }
    
    /**
     * @description Test checkPreSaveConflicts - With null parameters
     */
    @IsTest
    static void testCheckPreSaveConflicts_NullParams() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result = Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(opp.Id, null, null, null);
        Test.stopTest();
        
        System.assertEquals(false, result.hasProducingConflicts, 'Null treated as false');
        System.assertEquals(false, result.hasPlacingConflicts, 'Null treated as false');
        System.assertEquals(0, result.producingConflicts.size(), 'Empty list');
        System.assertEquals(0, result.placingPanelConflicts.size(), 'Empty list');
    }
    
    /**
     * @description Test resolvePreSaveConflicts - With null parameters
     */
    @IsTest
    static void testResolvePreSaveConflicts_NullParams() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Integer initialCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(opp.Id, null, null, null);
        Test.stopTest();
        
        Integer finalCount = [
            SELECT COUNT()
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        
        System.assertEquals(initialCount, finalCount, 'Null params should not delete');
    }
    
    // /**
    //  * @description Test getInitData - Options Structure (SettlementType + Cobroker)
    //  */
    // @IsTest
    // static void testGetInitData_OptionsStructure() {
        //     Test.startTest();
        //     Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(null);
        //     Test.stopTest();
        
        //     System.assertNotEquals(null, w.settlementTypeOptions, 'Not null');
        //     if (w.settlementTypeOptions.size() > 0) {
            //         System.assertNotEquals(null, w.settlementTypeOptions[0].label, 'Has label');
            //         System.assertNotEquals(null, w.settlementTypeOptions[0].value, 'Has value');
        //     }
        
        //     System.assertNotEquals(null, w.cobrokerOptions, 'Not null');
        //     if (w.cobrokerOptions.size() > 0) {
            //         System.assertNotEquals(null, w.cobrokerOptions[0].label, 'Has label');
            //         System.assertNotEquals(null, w.cobrokerOptions[0].value, 'Has value');
        //     }
    // }
    
    /**
     * @description Test getInitData - Force Exception with restricted user
     */
    @IsTest
    static void testGetInitData_ForceException() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        // Create a user with minimal permissions
        Profile p = [
            SELECT Id
            FROM Profile
            WHERE Name = 'Standard User' OR Name = 'Chatter Free User'
            LIMIT 1
        ];
        User restrictedUser = new User(
            Alias = 'tstu',
        Email = 'testuser@example.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'TestUser',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = p.Id,
        TimeZoneSidKey = 'America/Los_Angeles',
        UserName = 'testuser' + DateTime.now().getTime() + '@example.com'
            );
        insert restrictedUser;
        
        Test.startTest();
        System.runAs(restrictedUser) {
            try {
                Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(opp.Id);
                System.assertNotEquals(null, w, 'Should return a wrapper even with restricted access');
            } catch (AuraHandledException e) {
                System.assert(e.getMessage().contains('Error loading init data'), 'Should have appropriate error message');
            }
        }
        Test.stopTest();
    }
    
    /**
     * @description Test checkPreSaveConflicts - Force Exception path
     */
    @IsTest
    static void testCheckPreSaveConflicts_ForceException() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        // Create a user with minimal permissions
        Profile p = [
            SELECT Id
            FROM Profile
            WHERE Name = 'Standard User' OR Name = 'Chatter Free User'
            LIMIT 1
        ];
        User restrictedUser = new User(
            Alias = 'tstu3',
        Email = 'testuser3@example.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'TestUser3',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = p.Id,
        TimeZoneSidKey = 'America/Los_Angeles',
        UserName = 'testuser3' + DateTime.now().getTime() + '@example.com'
            );
        insert restrictedUser;
        
        Test.startTest();
        System.runAs(restrictedUser) {
            try {
                Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result = Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(opp.Id, null, true, true);
                // If no exception, verify the result
                System.assertNotEquals(null, result, 'Should return a wrapper object');
            } catch (AuraHandledException e) {
                // Exception path covered
                System.assert(e.getMessage().contains('Error checking pre-save conflicts'), 'Should have appropriate error message');
            }
        }
        Test.stopTest();
    }
    
    /**
     * @description Test all exception paths comprehensively
     */
    @IsTest
    static void testExceptionCoverage_Comprehensive() {
        Test.startTest();
        
        // getInitData exception path
        try {
            Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(null);
            System.assertNotEquals(null, w, 'Should handle null gracefully');
            System.assertNotEquals(null, w.coBrokerList, 'coBrokerList should not be null');
            System.assertEquals(false, w.producingDisabled, 'Should return false for null ID');
        } catch (Exception e) {
            System.assert(true, 'Exception caught and handled');
        }
        
        // checkPreSaveConflicts exception path
        try {
            Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result = Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(null, null, true, true);
            System.assertNotEquals(null, result, 'Should handle null gracefully');
        } catch (Exception e) {
            System.assert(true, 'Exception caught and handled');
        }
        
        Test.stopTest();
    }
    
    // ─────────────────────────────────────────────────────────────────────────
    // catch block 커버리지 (Exception 경로)
    // ─────────────────────────────────────────────────────────────────────────
    /**
     * @description deleteCoBrokers - catch (Exception e) 커버
     *              OPP_Cobroker__c OLS 미부여 사용자 → SOQL QueryException 유도
     */
    @IsTest
    static void testDeleteCoBrokers_ExceptionCatch() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        OPP_Cobroker__c cb = [
            SELECT Id
            FROM OPP_Cobroker__c
            WHERE Opportunity_md__c = :opp.Id AND LKCobroking_is__c = TRUE
            LIMIT 1
        ];
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' OR Name = 'Chatter Free User' LIMIT 1];
        User restrictedUser = new User(
            Alias = 'delexc',
        Email = 'delexc@lktest.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'DelExcUser',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = p.Id,
        TimeZoneSidKey = 'Asia/Seoul',
        UserName = 'delexc' + System.currentTimeMillis() + '@lktest.com'
            );
        insert restrictedUser;
        
        Test.startTest();
        System.runAs(restrictedUser) {
            try {
                Opp_LkCoBroking_Ctrl.deleteCoBrokers(new List<Id>{ cb.Id }, opp.Id, null);
                // 권한이 있으면 삭제 성공 — 성공 경로도 유효
                System.assert(true, '권한 있는 사용자: 정상 실행');
            } catch (AuraHandledException e) {
                // 권한 없으면 QueryException → catch (Exception e) 경로
                System.assert(e.getMessage().contains('Script-thrown exception'), 'Exception catch 경로 실행 확인: ' + e.getMessage());
            }
        }
        Test.stopTest();
    }
    
    // ─────────────────────────────────────────────────────────────────────────
    // Placement / Claim 컨텍스트 경로 커버
    // ─────────────────────────────────────────────────────────────────────────
    
    /**
     * @description [Placement 컨텍스트] getInitData에 Placement__c Id 전달
     *              → isPlacement=true, placementClosingDate 세팅,
     *                coBrokerList는 Placement_lk__c 기준 조회 검증
     */
    @IsTest
    static void testGetInitData_WithPlacementId_IsPlacementTrue() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        Placement__c placement = new Placement__c(
            Opportunity_lk__c      = opp.Id,
        PlacementClosingDate__c = Date.today()
            );
        insert placement;
        
        // Placement에 연결된 LK Co-Broker 생성
        OPP_Cobroker__c lkCb = new OPP_Cobroker__c(
            Placement_lk__c   = placement.Id,
        Opportunity_md__c = opp.Id,
        LKCobroking_is__c = true,
        CobrokingType__c  = 'Placing',
        SettlementType__c = 'Together',
        SharingPct__c     = 10,
        Client__c         = false
            );
        insert lkCb;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(placement.Id);
        Test.stopTest();
        
        Assert.isTrue(w.isPlacement,                           'isPlacement=true 기대');
        Assert.isFalse(w.isClaim,                              'isClaim=false 기대');
        Assert.areEqual(Date.today(), w.placementClosingDate,  'placementClosingDate 세팅 기대');
        Assert.isTrue(w.coBrokerList.size() >= 1,              'Placement 기준 coBrokerList 1건 이상 기대');
    }
    
    /**
     * @description [Claim 컨텍스트] getInitData에 Claim Id 전달
     *              → isClaim=true, hasEditPermission=false,
     *                Claim.Placement_lk__c 기준 placementId 세팅 후 coBrokerList 조회 검증
     */
    @IsTest
    static void testGetInitData_WithClaimId_IsClaimTrue() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        Placement__c placement = new Placement__c(Opportunity_lk__c = opp.Id);
        insert placement;
        
        Claim claim = new Claim(Placement_lk__c = placement.Id, Name = 'Test Claim');
        insert claim;
        
        OPP_Cobroker__c lkCb = new OPP_Cobroker__c(
            Placement_lk__c   = placement.Id,
        Opportunity_md__c = opp.Id,
        LKCobroking_is__c = true,
        CobrokingType__c  = 'Placing',
        SettlementType__c = 'Together',
        SharingPct__c     = 5,
        Client__c         = false
            );
        insert lkCb;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(claim.Id);
        Test.stopTest();
        
        Assert.isTrue(w.isClaim,              'isClaim=true 기대');
        Assert.isFalse(w.hasEditPermission,   'Claim 컨텍스트는 hasEditPermission=false 기대');
        Assert.isTrue(w.coBrokerList.size() >= 1, 'Placement 기준 coBrokerList 1건 이상 기대');
    }
    
    // ─────────────────────────────────────────────────────────────────────────
    // getAccountInternalRegion 경로 커버
    // ─────────────────────────────────────────────────────────────────────────
    
    /**
     * @description [null] accountId=null → null 반환 검증
     */
    @IsTest
    static void testGetAccountInternalRegion_NullId_ReturnsNull() {
        Test.startTest();
        String result = Opp_LkCoBroking_Ctrl.getAccountInternalRegion(null);
        Test.stopTest();
        
        Assert.isNull(result, 'null accountId → null 반환 기대');
    }
    
    /**
     * @description [유효값] LKInternalRegion__c가 설정된 Account 조회 → 값 반환 검증
     */
    @IsTest
    static void testGetAccountInternalRegion_ValidAccount_ReturnsRegion() {
        Account acc = ACC_TestDataFactory.createAccount('Region Test Account', 'General', false);
        acc.LKInternalRegion__c = 'LK_KR';
        insert acc;
        
        Test.startTest();
        String result = Opp_LkCoBroking_Ctrl.getAccountInternalRegion(acc.Id);
        Test.stopTest();
        
        Assert.areEqual('LK_KR', result, 'LKInternalRegion__c 값 반환 기대');
    }
    
    /**
     * @description [미존재] 삭제된 Account Id → isEmpty()=true → null 반환 검증
     */
    @IsTest
    static void testGetAccountInternalRegion_NotFound_ReturnsNull() {
        Account acc = ACC_TestDataFactory.createAccount('Temp Account For Delete', 'General', false);
        insert acc;
        Id deletedId = acc.Id;
        delete acc;
        
        Test.startTest();
        String result = Opp_LkCoBroking_Ctrl.getAccountInternalRegion(deletedId);
        Test.stopTest();
        
        Assert.isNull(result, 'Account 미존재 → null 반환 기대');
    }
    
    // ─────────────────────────────────────────────────────────────────────────
    // saveCoBrokers / deleteCoBrokers — Placement 컨텍스트 경로 커버
    // ─────────────────────────────────────────────────────────────────────────
    
    /**
     * @description [Placement 컨텍스트] saveCoBrokers에 placementId 전달
     *              → isPlacement=true → Placement.Opportunity_lk__c 조회 → oppId 설정
     *              → 신규 레코드에 Placement_lk__c / Opportunity_md__c 세팅 검증
     */
    @IsTest
    static void testSaveCoBrokers_WithPlacementId_InsertNew() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        Placement__c placement = new Placement__c(Opportunity_lk__c = opp.Id);
        insert placement;
        
        OPP_Cobroker__c newCb = new OPP_Cobroker__c(
            CobrokingType__c  = 'Placing',
        SettlementType__c = 'Together',
        SharingPct__c     = 20,
        Client__c         = false
            );
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ newCb }, null, placement.Id, false);
        Test.stopTest();
        
        List<OPP_Cobroker__c> saved = [
            SELECT Id, Placement_lk__c, Opportunity_md__c, LKCobroking_is__c
            FROM OPP_Cobroker__c
            WHERE Placement_lk__c = :placement.Id AND LKCobroking_is__c = TRUE
        ];
        Assert.areEqual(1, saved.size(),                   '신규 레코드 1건 저장 기대');
        Assert.areEqual(placement.Id, saved[0].Placement_lk__c, 'Placement_lk__c 세팅 기대');
        Assert.areEqual(opp.Id,       saved[0].Opportunity_md__c, 'Opportunity_md__c 세팅 기대');
    }
    
    /**
     * @description [Placement 컨텍스트] deleteCoBrokers에 placementId 전달
     *              → WHERE Placement_lk__c = :placementId 기준 삭제 검증
     */
    @IsTest
    static void testDeleteCoBrokers_WithPlacementId_Success() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        Placement__c placement = new Placement__c(Opportunity_lk__c = opp.Id);
        insert placement;
        
        OPP_Cobroker__c cb = new OPP_Cobroker__c(
            Placement_lk__c   = placement.Id,
        Opportunity_md__c = opp.Id,
        LKCobroking_is__c = true,
        CobrokingType__c  = 'Placing',
        SettlementType__c = 'Together',
        SharingPct__c     = 10,
        Client__c         = false
            );
        insert cb;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.deleteCoBrokers(new List<Id>{ cb.Id }, null, placement.Id);
        Test.stopTest();
        
        List<OPP_Cobroker__c> afterDelete = [SELECT Id FROM OPP_Cobroker__c WHERE Id = :cb.Id];
        Assert.areEqual(0, afterDelete.size(), 'Placement 컨텍스트 삭제 기대');
    }
    
    // ─────────────────────────────────────────────────────────────────────────
    // checkPreSaveConflicts / resolvePreSaveConflicts — Placement 컨텍스트 경로 커버
    // ─────────────────────────────────────────────────────────────────────────
    
    /**
     * @description [Placement 컨텍스트] checkPreSaveConflicts에 placementId 전달 + 양쪽 충돌 존재
     *              → isPlacement=true → Placement 기준 Producing/Placing 충돌 조회 검증
     */
    @IsTest
    static void testCheckPreSaveConflicts_WithPlacementId_HasBoth() {
        Opportunity opp   = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        Account cobrokerAcc = ACC_TestDataFactory.createAccount('PlacementCheck CoBroker', 'Broker', true);
        
        Placement__c placement = new Placement__c(Opportunity_lk__c = opp.Id);
        insert placement;
        
        // Producing 충돌: LKCobroking_is__c=false
        OPP_Cobroker__c producingConflict = new OPP_Cobroker__c(
            Placement_lk__c   = placement.Id,
        Opportunity_md__c = opp.Id,
        LKCobroking_is__c = false,
        CobrokingType__c  = 'Producing',
        SettlementType__c = 'Separate',
        SharingPct__c     = 10,
        Client__c         = false,
        CobrokerName_lk__c = cobrokerAcc.Id
            );
        insert producingConflict;
        
        // Placing 충돌: Layer.Placement_lk__c → Panel.CoBroker_lk__c != null
        OPP_Layer__c layer = OPP_TestDataFactory.createLayer(opp.Id, false);
        layer.Placement_lk__c = placement.Id;
        insert layer;
        
        OPP_Panel__c panel = OPP_TestDataFactory.createPanel(layer.Id, false);
        panel.CoBroker_lk__c = cobrokerAcc.Id;
        insert panel;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.ConflictCheckWrapper result =
            Opp_LkCoBroking_Ctrl.checkPreSaveConflicts(null, placement.Id, true, true);
        Test.stopTest();
        
        Assert.isTrue(result.hasAny,                     'Placement 컨텍스트 충돌 존재 기대');
        Assert.isTrue(result.hasProducingConflicts,      'Producing 충돌 존재 기대');
        Assert.isTrue(result.hasPlacingConflicts,        'Placing 충돌 존재 기대');
        Assert.areEqual(1, result.producingConflicts.size(),    'Producing 충돌 1건 기대');
        Assert.areEqual(1, result.placingPanelConflicts.size(), 'Placing 충돌 1건 기대');
    }
    
    /**
     * @description [Placement 컨텍스트] resolvePreSaveConflicts에 placementId 전달 + 양쪽 해소
     *              → isPlacement=true → Producing OPP_Cobroker__c 삭제 + Panel CoBroker 초기화 검증
     */
    @IsTest
    static void testResolvePreSaveConflicts_WithPlacementId_ResolveBoth() {
        Opportunity opp     = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        Account cobrokerAcc = ACC_TestDataFactory.createAccount('PlacementResolve CoBroker', 'Broker', true);
        
        Placement__c placement = new Placement__c(Opportunity_lk__c = opp.Id);
        insert placement;
        
        OPP_Cobroker__c producingConflict = new OPP_Cobroker__c(
            Placement_lk__c   = placement.Id,
        Opportunity_md__c = opp.Id,
        LKCobroking_is__c = false,
        CobrokingType__c  = 'Producing',
        SettlementType__c = 'Separate',
        SharingPct__c     = 10,
        Client__c         = false
            );
        insert producingConflict;
        
        OPP_Layer__c layer = OPP_TestDataFactory.createLayer(opp.Id, false);
        layer.Placement_lk__c = placement.Id;
        insert layer;
        
        OPP_Panel__c panel = OPP_TestDataFactory.createPanel(layer.Id, false);
        panel.CoBroker_lk__c       = cobrokerAcc.Id;
        panel.PlacingSharingPct__c = 10;
        insert panel;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(null, placement.Id, true, true);
        Test.stopTest();
        
        Integer producingCount = [
            SELECT COUNT() FROM OPP_Cobroker__c
            WHERE Placement_lk__c = :placement.Id AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
        ];
        Assert.areEqual(0, producingCount, 'Producing 충돌 삭제 기대');
        
        Integer placingCount = [
            SELECT COUNT() FROM OPP_Panel__c
            WHERE Layer_md__r.Placement_lk__c = :placement.Id AND CoBroker_lk__c != NULL
        ];
        Assert.areEqual(0, placingCount, 'Placing Panel CoBroker 초기화 기대');
    }
    
    /**
     * @description resolvePreSaveConflicts - catch (Exception e) 커버
     *              OPP_Cobroker__c OLS 미부여 사용자 → SOQL QueryException 유도
     */
    @IsTest
    static void testResolvePreSaveConflicts_ExceptionCatch() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User' OR Name = 'Chatter Free User' LIMIT 1];
        User restrictedUser = new User(
            Alias = 'rslexc',
        Email = 'rslexc@lktest.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'RslExcUser',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = p.Id,
        TimeZoneSidKey = 'Asia/Seoul',
        UserName = 'rslexc' + System.currentTimeMillis() + '@lktest.com'
            );
        insert restrictedUser;
        
        Test.startTest();
        System.runAs(restrictedUser) {
            try {
                Opp_LkCoBroking_Ctrl.resolvePreSaveConflicts(opp.Id, null, true, true);
                System.assert(true, '권한 있는 사용자: 정상 실행');
            } catch (AuraHandledException e) {
                // 권한 없으면 QueryException → catch (Exception e) 경로
                System.assert(e.getMessage().contains('Script-thrown exception'), 'Exception catch 경로 실행 확인: ' + e.getMessage());
            }
        }
        Test.stopTest();
    }
    
    /**
     * @description saveCoBrokers 메서드 테스트 - needsRecalculate=true 시 Opportunity.NeedRecalculate_is__c 업데이트
     */
    @IsTest
    static void testSaveCoBrokers_NeedRecalculate() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        OPP_Cobroker__c newCoBroker = new OPP_Cobroker__c();
        newCoBroker.CobrokingType__c = 'Placing';
        newCoBroker.SettlementType__c = 'Together';
        newCoBroker.SharingPct__c = 10;
        newCoBroker.Client__c = false;
        newCoBroker.Sharing_is__c = false;
        
        Test.startTest();
        Opp_LkCoBroking_Ctrl.saveCoBrokers(new List<OPP_Cobroker__c>{ newCoBroker }, opp.Id, null, true);
        Test.stopTest();
        
        Opportunity updated = [SELECT NeedRecalculate_is__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals(true, updated.NeedRecalculate_is__c, 'needsRecalculate=true 시 NeedRecalculate_is__c가 true여야 함');
    }
    
    /**
     * @description Test getInitData - Exception handling with restricted user
     */
    @IsTest
    static void testGetInitData_ExceptionWithRestrictedAccess() {
        Opportunity opp = [SELECT Id FROM Opportunity ORDER BY CreatedDate ASC, Id ASC LIMIT 1];
        
        Profile minimalProfile = [
            SELECT Id
            FROM Profile
            WHERE Name = 'Standard User' OR Name = 'Chatter Free User'
            LIMIT 1
        ];
        
        User testUser = new User(
            Alias = 'exusr',
        Email = 'exceptionuser@test.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'ExceptionTestUser',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US',
        ProfileId = minimalProfile.Id,
        TimeZoneSidKey = 'Asia/Seoul',
        UserName = 'exceptionuser' + System.currentTimeMillis() + '@lktest.com'
            );
        insert testUser;
        
        Test.startTest();
        System.runAs(testUser) {
            try {
                Opp_LkCoBroking_Ctrl.InitDataWrapper w = Opp_LkCoBroking_Ctrl.getInitData(opp.Id);
                System.assertNotEquals(null, w, 'Result should not be null even with restricted access');
            } catch (AuraHandledException e) {
                System.assert(e.getMessage().contains('Error loading init data'), 'Exception message should contain expected text: ' + e.getMessage());
            }
        }
        Test.stopTest();
    }
}