force-app/main/default/objects/Account/fields/LKInternalRegion__c.field-meta.xml
<CustomField>
    <fullName>LKInternalRegion__c</fullName>
    <label>LK Internal Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_BizRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Claim/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LK Ref. Name</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/OPP_Cobroker__c.object-meta.xml
<CustomObject>
    <label>Co-Broker</label>
    <nameField>
        <displayFormat>COB-{00000000}</displayFormat>
        <label>Co-Broker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co-Broker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Cobroker__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/CobrokerContact_lk__c.field-meta.xml
<CustomField>
    <fullName>CobrokerContact_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Co-Broker</relationshipLabel>
    <relationshipName>CoBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/CobrokerName_lk__c.field-meta.xml
<CustomField>
    <fullName>CobrokerName_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Co-Broker</relationshipLabel>
    <relationshipName>CoBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/CobrokerUser_lk__c.field-meta.xml
<CustomField>
    <fullName>CobrokerUser_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CoBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/CobrokingType__c.field-meta.xml
<CustomField>
    <fullName>CobrokingType__c</fullName>
    <label>Co-broking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producing</fullName>
            </value>
            <value>
                <fullName>Placing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/LKAdminFeePct__c.field-meta.xml
<CustomField>
    <fullName>LKAdminFeePct__c</fullName>
    <label>LK Admin Fee(%)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/LKCobroker_lk__c.field-meta.xml
<CustomField>
    <fullName>LKCobroker_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Co-Broker (Co-broker)</relationshipLabel>
    <relationshipName>CoBrokerByLKCobroker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/LKCobroking_is__c.field-meta.xml
<CustomField>
    <fullName>LKCobroking_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LK Co-Broking</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/Opportunity_md__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_md__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Co-Broker</relationshipLabel>
    <relationshipName>CoBrokers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Co-Broker</relationshipLabel>
    <relationshipName>CoBrokers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/SettlementType__c.field-meta.xml
<CustomField>
    <fullName>SettlementType__c</fullName>
    <label>Settlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Together</fullName>
            </value>
            <value>
                <fullName>Separate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/Sharing_is__c.field-meta.xml
<CustomField>
    <fullName>Sharing_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sharing Y/N</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Cobroker__c/fields/SharingPct__c.field-meta.xml
<CustomField>
    <fullName>SharingPct__c</fullName>
    <label>Sharing(%)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/OPP_Layer__c.object-meta.xml
<CustomObject>
    <label>Layer</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Layer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Layers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Layer__c/fields/Opportunity_md__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_md__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Layers</relationshipLabel>
    <relationshipName>Layers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Layers</relationshipLabel>
    <relationshipName>LayersAsPlacement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/OPP_Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Panel__c/fields/CoBroker_lk__c.field-meta.xml
<CustomField>
    <fullName>CoBroker_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-broker</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Panels (Co-borker Name)</relationshipLabel>
    <relationshipName>PanelsAsCoBroker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/CoBrokerContact_lk__c.field-meta.xml
<CustomField>
    <fullName>CoBrokerContact_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placing Co-broker Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Panels (Placing Co-broker Contact)</relationshipLabel>
    <relationshipName>PanelsAsCoBroker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/CobrokingType__c.field-meta.xml
<CustomField>
    <fullName>CobrokingType__c</fullName>
    <label>Co-Broking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPO</fullName>
            </value>
            <value>
                <fullName>CPS</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>CPT-CPO</fullName>
            </value>
            <value>
                <fullName>CPT-CPS</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Layer_md__c.field-meta.xml
<CustomField>
    <fullName>Layer_md__c</fullName>
    <label>Layer</label>
    <referenceTo>OPP_Layer__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Opportunity_lk__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/PlacingSettlementType__c.field-meta.xml
<CustomField>
    <fullName>PlacingSettlementType__c</fullName>
    <label>Settlement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Separate</fullName>
            </value>
            <value>
                <fullName>Together</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/PlacingSharingPct__c.field-meta.xml
<CustomField>
    <fullName>PlacingSharingPct__c</fullName>
    <label>Sharing(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/PlacingTPPAdminFeePct__c.field-meta.xml
<CustomField>
    <fullName>PlacingTPPAdminFeePct__c</fullName>
    <label>TPP Admin Fee(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LKCobroker_lk__c.field-meta.xml
<CustomField>
    <fullName>LKCobroker_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Co-Owner</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (7 AND 8)</booleanFilter>
        <filterItems>
            <field>$User.Region__c</field>
            <operation>equals</operation>
            <value>SG</value>
        </filterItems>
        <filterItems>
            <field>User.Region__c</field>
            <operation>equals</operation>
            <value>SG</value>
        </filterItems>
        <filterItems>
            <field>$User.Region__c</field>
            <operation>equals</operation>
            <value>KR</value>
        </filterItems>
        <filterItems>
            <field>User.Region__c</field>
            <operation>equals</operation>
            <value>KR</value>
        </filterItems>
        <filterItems>
            <field>$User.Region__c</field>
            <operation>equals</operation>
            <value>VN</value>
        </filterItems>
        <filterItems>
            <field>User.Region__c</field>
            <operation>equals</operation>
            <value>VN</value>
        </filterItems>
        <filterItems>
            <field>$User.Region__c</field>
            <operation>equals</operation>
            <value>A&amp;G</value>
        </filterItems>
        <filterItems>
            <field>User.Region__c</field>
            <operation>equals</operation>
            <value>A&amp;G</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NeedRecalculate_is__c.field-meta.xml
<CustomField>
    <fullName>NeedRecalculate_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Recalculate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <label>LK Ref. Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/CoBrokingType__c.field-meta.xml
<CustomField>
    <fullName>CoBrokingType__c</fullName>
    <label>Co-Broking Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPO</fullName>
            </value>
            <value>
                <fullName>CPS</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CI</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>CPT-CPO</fullName>
            </value>
            <value>
                <fullName>CPT-CPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/NeedRecalculate_is__c.field-meta.xml
<CustomField>
    <fullName>NeedRecalculate_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Recalculate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Opportunity_lk__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/PlacementClosingDate__c.field-meta.xml
<CustomField>
    <fullName>PlacementClosingDate__c</fullName>
    <label>Send to Close date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/COM_BizRegion.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LK_KR</fullName>
    </customValue>
    <customValue>
        <fullName>LK_Re</fullName>
    </customValue>
    <customValue>
        <fullName>LK_VN</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <masterLabel>[COM] Biz Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Opp_LkCoBroking_Ctrl.cls
/**********************************************************************************
 * @filename      : Opp_LkCoBroking_Ctrl.cls
 * @project-name  : LK_DEV2
 * @author        : i2max
 * @date          : 2025-12-23
 * @group         :
 * @group-content :
 * @description   : LK Co-Broking 데이터 조회, 저장 및 충돌 처리를 담당하는 컨트롤러
 * @test-class    : Opp_LkCoBroking_Ctrl_ts.cls
 * @reference     :
 * @copyright     : LK Insurance Services
 * @modification  Log
 * ===================================================================
 * ver   date            author           description
 * ===================================================================
 * 1.0   2025-12-23      i2max            Create
 **********************************************************************************/
public with sharing class Opp_LkCoBroking_Ctrl {
    
    // ============================================================
    // Methods
    // ============================================================
    
    /**
     * @description 초기 화면 로딩에 필요한 LK Co-Broking 데이터를 조회한다.
     * @param recordId Opportunity, Placement__c 또는 Claim 레코드 Id
     * @return InitDataWrapper 초기 화면 데이터
     */
    @AuraEnabled(Cacheable=true)
    public static InitDataWrapper getInitData(Id recordId) {
        try {
            InitDataWrapper w = new InitDataWrapper();
            
            if (String.isBlank(recordId))
                return w;
            
            Id placementId;
            String sObjectName = COM_MetaUtil.getObjectNameById(recordId);
            w.isPlacement = 'Placement__c'.equalsIgnoreCase(sObjectName);
            w.isClaim = 'Claim'.equalsIgnoreCase(sObjectName);
            
            if (w.isClaim) {
                Claim claim = [SELECT Placement_lk__c FROM Claim WHERE Id = :recordId];
                placementId = claim.Placement_lk__c;
            }
            
            if (w.isPlacement || w.isClaim) {
                if (w.isPlacement)
                    placementId = recordId;
                
                // Placement의 PlacementClosingDate__c 조회
                if (placementId != null) {
                    Placement__c placement = [SELECT PlacementClosingDate__c FROM Placement__c WHERE Id = :placementId];
                    w.placementClosingDate = placement.PlacementClosingDate__c;
                }
                
                // Placement / Claim 컨텍스트: Placement_lk__c 기준 조회 (readonly)
                w.coBrokerList = [
                    SELECT
                        Id,
                        Name,
                        CobrokingType__c,
                        LKCobroker_lk__c,
                        LKCobroker_lk__r.Name,
                        CobrokerUser_lk__c,
                        CobrokerUser_lk__r.Name,
                        SettlementType__c,
                        Client__c,
                        Sharing_is__c,
                        SharingPct__c,
                        Opportunity_md__c
                    FROM OPP_Cobroker__c
                    WHERE Placement_lk__c = :placementId AND LKCobroking_is__c = TRUE AND Placement_lk__c != NULL
                    ORDER BY CobrokingType__c, CreatedDate
                ];
            } else {
                // Opportunity 컨텍스트
                w.coBrokerList = [
                    SELECT
                        Id,
                        Name,
                        CobrokingType__c,
                        LKCobroker_lk__c,
                        LKCobroker_lk__r.Name,
                        CobrokerUser_lk__c,
                        CobrokerUser_lk__r.Name,
                        SettlementType__c,
                        Client__c,
                        Sharing_is__c,
                        SharingPct__c,
                        Opportunity_md__c
                    FROM OPP_Cobroker__c
                    WHERE Opportunity_md__c = :recordId AND LKCobroking_is__c = TRUE AND Placement_lk__c = NULL
                    ORDER BY CobrokingType__c, CreatedDate
                ];
                
                Integer count = [
                    SELECT COUNT()
                    FROM OPP_Cobroker__c
                    WHERE Opportunity_md__c = :recordId AND CobrokingType__c = 'Producing' AND SettlementType__c = 'Separate' AND Client__c = TRUE AND LKCobroking_is__c = FALSE
                    LIMIT 1
                ];
                w.producingDisabled = count > 0;
            }
            
            w.settlementTypeOptions = COM_Util.makePickListOptions('OPP_Cobroker__c', 'SettlementType__c', false);
            w.hasEditPermission = w.isClaim ? false : COM_MetaUtil.checkEditPermission(recordId);
            
            return w;
        } catch (Exception e) {
            throw new AuraHandledException('Error loading init data: ' + e.getMessage());
        }
    }
    
    /**
     * @description Account의 LKInternalRegion__c 값을 조회한다.
     * @param accountId Account Id
     * @return String LKInternalRegion__c 값
     */
    @AuraEnabled(Cacheable=true)
    public static String getAccountInternalRegion(Id accountId) {
        if (accountId == null) return null;
        List<Account> accounts = [
            SELECT LKInternalRegion__c
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];
        return accounts.isEmpty() ? null : accounts[0].LKInternalRegion__c;
    }
    
    /**
     * @description LK Co-Broker 레코드를 저장하거나 수정한다.
     * @param coBrokers 저장할 Co-Broker 레코드 목록
     * @param oppId Opportunity 컨텍스트의 Opportunity Id
     * @param placementId Placement 컨텍스트의 Placement__c Id
     * @param needsRecalculate 재계산 필요 여부
     * @return 없음
     */
    @AuraEnabled
    public static void saveCoBrokers(List<OPP_Cobroker__c> coBrokers, Id oppId, Id placementId, Boolean needsRecalculate) {
        if (coBrokers == null || coBrokers.isEmpty()) {
            throw new AuraHandledException('No Co-Broker records to save.');
        }
        
        Boolean isPlacement = placementId != null;
        
        if (isPlacement) {
            Placement__c placement = [SELECT Opportunity_lk__c FROM Placement__c WHERE Id = :placementId LIMIT 1];
            oppId = placement.Opportunity_lk__c;
        }
        
        List<OPP_Cobroker__c> recordsToUpsert = new List<OPP_Cobroker__c>();
        
        for (OPP_Cobroker__c cb : coBrokers) {
            OPP_Cobroker__c record = new OPP_Cobroker__c();
            
            if (cb.Id != null) {
                record.Id = cb.Id;
            } else if (isPlacement) {
                record.Placement_lk__c = placementId;
                record.Opportunity_md__c = oppId;
            } else {
                record.Opportunity_md__c = oppId;
            }
            
            record.CobrokingType__c = cb.CobrokingType__c;
            record.LKCobroker_lk__c = cb.LKCobroker_lk__c;
            record.CobrokerUser_lk__c = cb.CobrokerUser_lk__c;
            record.SettlementType__c = cb.SettlementType__c;
            record.Client__c = cb.Client__c == null ? false : cb.Client__c;
            record.SharingPct__c = cb.SharingPct__c == null ? 0 : cb.SharingPct__c;
            record.Sharing_is__c = record.SharingPct__c > 0;
            record.LKCobroking_is__c = true;
            
            recordsToUpsert.add(record);
        }
        
        try {
            upsert recordsToUpsert;
        } catch (DmlException e) {
            throw new AuraHandledException('Error saving Co-Brokers: ' + e.getDmlMessage(0));
        } catch (Exception e) {
            throw new AuraHandledException('Error saving Co-Brokers: ' + e.getMessage());
        }
        
        if (needsRecalculate == true && !isPlacement && oppId != null) {
            update new Opportunity(Id = oppId, NeedRecalculate_is__c = true);
        }
    }
    
    /**
     * @description 지정한 LK Co-Broker 레코드를 삭제한다.
     * @param coBrokerIds 삭제할 Co-Broker Id 목록
     * @param oppId Opportunity 컨텍스트의 Opportunity Id
     * @param placementId Placement 컨텍스트의 Placement__c Id
     * @return 없음
     */
    @AuraEnabled
    public static void deleteCoBrokers(List<Id> coBrokerIds, Id oppId, Id placementId) {
        if (coBrokerIds == null || coBrokerIds.isEmpty())
            return;
        
        try {
            if (placementId != null) {
                delete [SELECT Id FROM OPP_Cobroker__c WHERE Id IN :coBrokerIds AND Placement_lk__c = :placementId AND LKCobroking_is__c = TRUE];
            } else {
                delete [SELECT Id FROM OPP_Cobroker__c WHERE Id IN :coBrokerIds AND Opportunity_md__c = :oppId AND LKCobroking_is__c = TRUE];
            }
        } catch (DmlException e) {
            throw new AuraHandledException('Error deleting Co-Brokers: ' + e.getDmlMessage(0));
        } catch (Exception e) {
            throw new AuraHandledException('Error deleting Co-Brokers: ' + e.getMessage());
        }
    }
    
    /**
     * @description 저장 전 Producing 및 Placing 충돌 데이터를 조회한다.
     * @param oppId Opportunity 컨텍스트의 Opportunity Id
     * @param placementId Placement 컨텍스트의 Placement__c Id
     * @param checkProducing Producing 충돌 체크 여부
     * @param checkPlacing Placing 충돌 체크 여부
     * @return ConflictCheckWrapper 충돌 조회 결과
     */
    @AuraEnabled
    public static ConflictCheckWrapper checkPreSaveConflicts(Id oppId, Id placementId, Boolean checkProducing, Boolean checkPlacing) {
        try {
            ConflictCheckWrapper w = new ConflictCheckWrapper();
            Boolean isPlacement = placementId != null;
            Id contextId = isPlacement ? placementId : oppId;
            if (String.isBlank(contextId))
                return w;
            
            checkProducing = (checkProducing == true);
            checkPlacing = (checkPlacing == true);
            
            if (checkProducing) {
                w.producingConflicts = isPlacement
                    ? [
                          SELECT Id, Name, CobrokerName_lk__c, CobrokerName_lk__r.Name, CobrokerContact_lk__c, CobrokerContact_lk__r.Name, SharingPct__c, LKAdminFeePct__c, SettlementType__c, Client__c
                          FROM OPP_Cobroker__c
                          WHERE Placement_lk__c = :placementId AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
                          ORDER BY CreatedDate
                      ]
                    : [
                          SELECT Id, Name, CobrokerName_lk__c, CobrokerName_lk__r.Name, CobrokerContact_lk__c, CobrokerContact_lk__r.Name, SharingPct__c, LKAdminFeePct__c, SettlementType__c, Client__c
                          FROM OPP_Cobroker__c
                          WHERE Opportunity_md__c = :oppId AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE
                          ORDER BY CreatedDate
                      ];
                w.hasProducingConflicts = !w.producingConflicts.isEmpty();
            }
            
            if (checkPlacing) {
                w.placingPanelConflicts = isPlacement
                    ? [
                          SELECT Id, Name, CoBroker_lk__c, CoBroker_lk__r.Name, PlacingTPPAdminFeePct__c, PlacingSharingPct__c, PlacingSettlementType__c
                          FROM OPP_Panel__c
                          WHERE Layer_md__r.Placement_lk__c = :placementId AND CoBroker_lk__c != NULL
                          ORDER BY CreatedDate
                      ]
                    : [
                          SELECT Id, Name, CoBroker_lk__c, CoBroker_lk__r.Name, PlacingTPPAdminFeePct__c, PlacingSharingPct__c, PlacingSettlementType__c
                          FROM OPP_Panel__c
                          WHERE Layer_md__r.Opportunity_md__c = :oppId AND CoBroker_lk__c != NULL
                          ORDER BY CreatedDate
                      ];
                w.hasPlacingConflicts = !w.placingPanelConflicts.isEmpty();
            }
            
            w.hasAny = w.hasProducingConflicts || w.hasPlacingConflicts;
            return w;
        } catch (Exception e) {
            throw new AuraHandledException('Error checking pre-save conflicts: ' + e.getMessage());
        }
    }
    
    /**
     * @description 저장 전 조회된 Producing 및 Placing 충돌 데이터를 처리한다.
     * @param oppId Opportunity 컨텍스트의 Opportunity Id
     * @param placementId Placement 컨텍스트의 Placement__c Id
     * @param resolveProducing Producing 충돌 해소 여부
     * @param resolvePlacing Placing 충돌 해소 여부
     * @return 없음
     */
    @AuraEnabled
    public static void resolvePreSaveConflicts(Id oppId, Id placementId, Boolean resolveProducing, Boolean resolvePlacing) {
        Boolean isPlacement = placementId != null;
        Savepoint sp = Database.setSavepoint();
        try {
            Id contextId = isPlacement ? placementId : oppId;
            if (String.isBlank(contextId))
                return;
            
            resolveProducing = (resolveProducing == true);
            resolvePlacing = (resolvePlacing == true);
            
            if (resolveProducing) {
                List<OPP_Cobroker__c> toDelete = isPlacement
                    ? [SELECT Id FROM OPP_Cobroker__c WHERE Placement_lk__c = :placementId AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE]
                    : [SELECT Id FROM OPP_Cobroker__c WHERE Opportunity_md__c = :oppId AND CobrokingType__c = 'Producing' AND LKCobroking_is__c = FALSE];
                if (!toDelete.isEmpty())
                    delete toDelete;
            }
            
            if (resolvePlacing) {
                List<OPP_Panel__c> panels = isPlacement
                    ? [
                          SELECT Id, CoBroker_lk__c, PlacingTPPAdminFeePct__c, PlacingSharingPct__c, PlacingSettlementType__c
                          FROM OPP_Panel__c
                          WHERE Layer_md__r.Placement_lk__c = :placementId AND CoBroker_lk__c != NULL
                      ]
                    : [
                          SELECT Id, CoBroker_lk__c, PlacingTPPAdminFeePct__c, PlacingSharingPct__c, PlacingSettlementType__c
                          FROM OPP_Panel__c
                          WHERE Layer_md__r.Opportunity_md__c = :oppId AND CoBroker_lk__c != NULL
                      ];
                if (!panels.isEmpty()) {
                    for (OPP_Panel__c p : panels) {
                        p.CoBroker_lk__c = null;
                        p.PlacingTPPAdminFeePct__c = null;
                        p.PlacingSharingPct__c = null;
                        p.PlacingSettlementType__c = null;
                    }
                    update panels;
                }
            }
        } catch (DmlException e) {
            Database.rollback(sp);
            throw new AuraHandledException('Error resolving conflicts: ' + e.getDmlMessage(0));
        } catch (Exception e) {
            Database.rollback(sp);
            throw new AuraHandledException('Error resolving conflicts: ' + e.getMessage());
        }
    }
    
    // ============================================================
    // Inner Classes
    // ============================================================
    
    /**
     * @description LK Co-Broking 초기 화면 데이터를 전달하는 Wrapper 클래스
     */
    public class InitDataWrapper {
        
        // ============================================================
        // Properties
        // ============================================================
        
        @AuraEnabled
        public List<OPP_Cobroker__c> coBrokerList { get; set; }
        @AuraEnabled
        public List<COM_Option> settlementTypeOptions { get; set; }
        @AuraEnabled
        public Boolean producingDisabled { get; set; }
        @AuraEnabled
        public Boolean isPlacement { get; set; }
        @AuraEnabled
        public Boolean isClaim { get; set; }
        @AuraEnabled
        public Boolean hasEditPermission { get; set; }
        @AuraEnabled
        public Date placementClosingDate { get; set; }
        
        // ============================================================
        // Methods
        // ============================================================
        
        /**
         * @description InitDataWrapper 기본값을 초기화한다.
         * @param 없음
         * @return 없음
         */
        public InitDataWrapper() {
            coBrokerList = new List<OPP_Cobroker__c>();
            settlementTypeOptions = new List<COM_Option>();
            producingDisabled = false;
            isPlacement = false;
            isClaim = false;
            hasEditPermission = false;
            placementClosingDate = null;
        }
    }
    
    /**
     * @description 저장 전 충돌 조회 결과를 전달하는 Wrapper 클래스
     */
    public class ConflictCheckWrapper {
        
        // ============================================================
        // Properties
        // ============================================================
        
        @AuraEnabled
        public Boolean hasAny { get; set; }
        @AuraEnabled
        public Boolean hasProducingConflicts { get; set; }
        @AuraEnabled
        public Boolean hasPlacingConflicts { get; set; }
        @AuraEnabled
        public List<OPP_Cobroker__c> producingConflicts { get; set; }
        @AuraEnabled
        public List<OPP_Panel__c> placingPanelConflicts { get; set; }
        
        // ============================================================
        // Methods
        // ============================================================
        
        /**
         * @description ConflictCheckWrapper 기본값을 초기화한다.
         * @param 없음
         * @return 없음
         */
        public ConflictCheckWrapper() {
            hasAny = false;
            hasProducingConflicts = false;
            hasPlacingConflicts = false;
            producingConflicts = new List<OPP_Cobroker__c>();
            placingPanelConflicts = new List<OPP_Panel__c>();
        }
    }
}