force-app/main/default/objects/BankTransaction__c/BankTransaction__c.object-meta.xml
<CustomObject>
    <label>Bank Transaction</label>
    <nameField>
        <displayFormat>BT-{YYMMDD}-{00000}</displayFormat>
        <label>Bank Transaction No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BankTransaction__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Transactions</relationshipLabel>
    <relationshipName>BankTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankTransaction__c/fields/Depositor__c.field-meta.xml
<CustomField>
    <fullName>Depositor__c</fullName>
    <label>Depositor</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReconciliationLineItem__c/ReconciliationLineItem__c.object-meta.xml
<CustomObject>
    <label>Reconciliation Line Item</label>
    <nameField>
        <displayFormat>RLI-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reconciliation Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReconciliationLineItem__c/fields/RefBankTransaction__c.field-meta.xml
<CustomField>
    <fullName>RefBankTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ref. Bank Transaction</label>
    <referenceTo>BankTransaction__c</referenceTo>
    <relationshipLabel>Reconciliation Line Items as Ref</relationshipLabel>
    <relationshipName>ReconciliationLineItemsAsRef</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReconciliationLineItem__c/fields/RLIStatus__c.field-meta.xml
<CustomField>
    <fullName>RLIStatus__c</fullName>
    <formula>Text(RefReconciliation__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RLI Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BankTransactionService.cls
public without sharing class BankTransactionService {
    public static final String TRANSACTION_TYPE_DEPOSIT = 'Deposit';
    public static final String TRANSACTION_TYPE_WITHDRAWAL = 'Withdrawal';

    public static List<BankTransaction__c> getBankTransaction(Set<String> setDepositor, Set<String> setBizRegion) {
        return [
            SELECT Id, BizRegion__c, Depositor__c, AccountName__c
            FROM BankTransaction__c
            WHERE Depositor__c IN :setDepositor AND BizRegion__c IN :setBizRegion
        ] ?? null;
    }

    public static List<BankTransaction__c> getBankTransactionNullAccountName(
        Set<String> setDepositor,
        Set<String> setBizRegion
    ) {
        return [
            SELECT Id, BizRegion__c, Depositor__c, AccountName__c
            FROM BankTransaction__c
            WHERE AccountName__c = NULL AND Depositor__c IN :setDepositor AND BizRegion__c IN :setBizRegion
        ] ?? null;
    }

    public static Set<Id> getSetConfirmedBankTransactionId(List<BankTransaction__c> listBankTransaction) {
        Set<Id> setConfirmedBtId = new Set<Id>();
        for (ReconciliationLineItem__c rli : getConfirmedReconLineItemRelatedBankTrnasaction(listBankTransaction)) {
            setConfirmedBtId.add(rli.RefBankTransaction__c);
        }

        return setConfirmedBtId;
    }

    public static List<ReconciliationLineItem__c> getConfirmedReconLineItemRelatedBankTrnasaction(
        List<BankTransaction__c> listBankTransaction
    ) {
        return new List<ReconciliationLineItem__c>(
            [
                SELECT RefBankTransaction__c
                FROM ReconciliationLineItem__c
                WHERE
                    RefBankTransaction__c IN :listBankTransaction
                    AND RLIStatus__c = 'Confirmed'
                    AND BizRegion__c = :Util.getBizRegion()
            ]
        );
    }
}