force-app/main/default/objects/OPP_Layer__c/OPP_Layer__c.object-meta.xml
<CustomObject>
    <label>Layer</label>
    <nameField>
        <displayFormat>LA-{00000000}</displayFormat>
        <label>Layer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Layers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Layer__c/fields/Opportunity_md__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_md__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Layers</relationshipLabel>
    <relationshipName>Layers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/fields/Placement_lk__c.field-meta.xml
<CustomField>
    <fullName>Placement_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Layers</relationshipLabel>
    <relationshipName>LayersAsPlacement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Layer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QS</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Excess</fullName>
            </value>
            <value>
                <fullName>Umbrella</fullName>
            </value>
            <value>
                <fullName>Brkg Adj</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/OPP_Panel__c.object-meta.xml
<CustomObject>
    <label>Panel</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Panel__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Layer_md__c.field-meta.xml
<CustomField>
    <fullName>Layer_md__c</fullName>
    <label>Layer</label>
    <referenceTo>OPP_Layer__c</referenceTo>
    <relationshipLabel>Panels</relationshipLabel>
    <relationshipName>Panels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OPP_Panel__c/fields/Reinsurer_lk__c.field-meta.xml
<CustomField>
    <fullName>Reinsurer_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reinsurer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>MarketLinesAsReinsurer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Subjectivity__c/OPP_Subjectivity__c.object-meta.xml
<CustomObject>
    <label>Subjectivity</label>
    <nameField>
        <label>Subjectivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjectivities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OPP_Subjectivity__c/fields/Clear_is__c.field-meta.xml
<CustomField>
    <fullName>Clear_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clear</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OPP_Subjectivity__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <label>Detail</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OPP_Subjectivity__c/fields/Panel_lk__c.field-meta.xml
<CustomField>
    <fullName>Panel_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Panel</label>
    <referenceTo>OPP_Panel__c</referenceTo>
    <relationshipLabel>Subjectivity</relationshipLabel>
    <relationshipName>Subjectivity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OPP_Subjectivity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addition</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>COM_Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reinsurer_lk__c.field-meta.xml
<CustomField>
    <fullName>Reinsurer_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reinsurer(Temp)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Reinsurer)</relationshipLabel>
    <relationshipName>OpportunitiesAsReinsurers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/COM_Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>JPY</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>SGD</fullName>
    </customValue>
    <customValue>
        <fullName>CZK</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>CNY</fullName>
    </customValue>
    <customValue>
        <fullName>RMB</fullName>
    </customValue>
    <customValue>
        <fullName>STG</fullName>
    </customValue>
    <masterLabel>[COM] Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OPP_MarketLineSubjMgmtModal_Ctrl.cls
/**********************************************************************************
 * @filename      : OPP_MarketLineSubjMgmtModal_Ctrl.cls
 * @project-name  : LK보험중계 신규계약관리시스템 구축
 * @author        : i2max
 * @date          : 2026-01-16 (금)
 * @group         :
 * @group-content :
 * @description   : 
 * @test-class    : OPP_MarketLineSubjMgmtModal_Ctrl_ts.cls
 * @reference     : 
 * @copyright     : LK Insurance Services
 * @modification  Log
 * ===================================================================
 * ver   date            author           description
 * ===================================================================
 * 1.0   2026-01-16      i2max     Create
**********************************************************************************/
public with sharing class OPP_MarketLineSubjMgmtModal_Ctrl {

    // ========== Subjectivity 팝업 관련 ==========
    @AuraEnabled
    public static Map<String, Object> getSubjectivities(Id recordId, Id panelId, Id reinsurerId) {
        Map<String, Object> results = new Map<String, Object>();

        // 1. 기본 유효성 검사
        if (String.isBlank(recordId) || String.isBlank(panelId) || String.isBlank(reinsurerId)) return new Map<String, Object>{ 'error' => 'Record ID is required.' };

        OPP_Panel__c currentPanel = [SELECT Id, Currency__c FROM OPP_Panel__c WHERE Id=:panelId LIMIT 1];

        String panelCurrency = COM_Util.toStr(currentPanel.Currency__c);

        String sObjectNm = COM_MetaUtil.getObjectNameById(recordId);
        Boolean isOpp = 'Opportunity'.equalsIgnoreCase(sObjectNm);

        // 2. 현재 Panel의 Layer ID 조회 => 기회 또는 Placement 레코드 하위에서 동일 reinsurerId를 가진 Panel 중에서 첫번째 등록된 Panel하위 OPP_Subjectivity__c 검색
        List<String> query = new List<String>();
        query.add('SELECT Id');
        query.add('FROM OPP_Panel__c');

        if(isOpp==true) query.add('WHERE Layer_md__r.Opportunity_md__c=:recordId');
        if(isOpp==true) query.add('AND Layer_md__r.Placement_lk__c=null');

        if(isOpp==false) query.add('WHERE Layer_md__r.Placement_lk__c=:recordId');

        query.add('AND Reinsurer_lk__c = :reinsurerId');
        //query.add('AND Currency__c =:panelCurrency ');
        query.add('ORDER BY CreatedDate ASC');
        query.add('LIMIT 1');

        List<OPP_Panel__c> targetPanels = Database.query(String.join(query, ' '));

        if (targetPanels.isEmpty()) return new Map<String, Object>{ 'error' => 'Panel information not found.' };

        Id targetPanelId = targetPanels.isEmpty() ? panelId : targetPanels[0].Id;

        System.debug('getSubjectivities >> recordId=['+ recordId +'], reinsurerId=['+ reinsurerId +'], panelCurrency=['+ panelCurrency +'], targetPanelId=['+ targetPanelId +']');

        // 4. Subjectivity 조회
        results.put('records', [
                SELECT Id, Name, Type__c, Detail__c, Clear_is__c
                FROM OPP_Subjectivity__c
                WHERE Panel_lk__c = :targetPanelId
                ORDER BY CreatedDate
        ]);

        // 5. 옵션 및 변경된 Panel ID 반환
        results.put('typeOptions', COM_Util.makePickListOptions('OPP_Subjectivity__c', 'Type__c', true));
        results.put('panelId', targetPanelId);

        return results;
    }

    @AuraEnabled
    public static void saveSubjectivities(List<OPP_Subjectivity__c> upsertList, List<OPP_Subjectivity__c> deleteList) {
        if (deleteList != null && !deleteList.isEmpty()) delete deleteList;
        if (upsertList != null && !upsertList.isEmpty()) upsert upsertList;
    }


}