force-app/main/default/objects/ACC_News__c/ACC_News__c.object-meta.xml
<CustomObject>
    <label>Account News</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Account News Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ACC_News__c/fields/Account_lk__c.field-meta.xml
<CustomField>
    <fullName>Account_lk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account News</relationshipLabel>
    <relationshipName>AccountNews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ACC_News__c/fields/OriginalLink__c.field-meta.xml
<CustomField>
    <fullName>OriginalLink__c</fullName>
    <label>Original Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ACC_News__c/fields/PubDate__c.field-meta.xml
<CustomField>
    <fullName>PubDate__c</fullName>
    <label>Pub Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ACC_News__c/fields/TitleOriginal__c.field-meta.xml
<CustomField>
    <fullName>TitleOriginal__c</fullName>
    <label>Title Original</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ACC_News_Ctrl.cls
/**********************************************************************************
 * @filename      : ACC_News_Ctrl.cls
 * @projectname   :
 * @author        : i2max
 * @date          : 2026-03-08 (일)
 * @group         :
 * @group-content :
 * @description   :
 * @test-class    : ACC_News_Ctrl_ts.cls
 * @reference     :
 * @copyright     :
 * @modification  Log
 * ===================================================================
 * ver   date            author           description
 * ===================================================================
 * 1.0   2026-03-08      i2max            Create
**********************************************************************************/
public with sharing class ACC_News_Ctrl {

    @AuraEnabled(Cacheable=true)
    public static List<ACC_News__c> getNewsByAccountId(Id accountId, Integer limitCount) {

        if (accountId == null) throw new AuraHandledException('AccountId is required.');
        Integer maxCount = (limitCount != null && limitCount > 0) ? limitCount : 1000;

        return [
                SELECT Id, Title__c, Description__c, Link__c, OriginalLink__c,
                        PubDate__c, TitleOriginal__c
                FROM ACC_News__c
                WHERE Account_lk__c = :accountId
                ORDER BY PubDate__c DESC
                LIMIT :maxCount
        ];
    }

}